### ISSUE TITLE
Add Zanata to CI

### ISSUE THREAD

**Issue by tdruiva** [coyim/coyim#244]
To updated Zanata[1] with the lasted string from CoyIM we should add it to our pipeline.
- how to install Zanata client (http://docs.zanata.org/projects/zanata-client/en/latest/installation/linux-installation/)
- to generate the lasted strings, go to dir `i18n` and then `make`

1- https://translate.zanata.org/zanata/iteration/view/coyim/v1

**Comment by tcz001** [comment]
my id is tcz001

**Comment by pixelrust** [comment]
I volunteer for the Italian translation. 
My Zanata username is pixelrust. I've never used it before.

**Comment by tdruiva** [comment]
@pixelrust nice! 

> I've never used Zanata before. 
Don't worry, it's simple to use! 
Also, would be nice to find out more friends to help us to reviewing :smile_cat: 

> My Zanata username is pixelrust
I'll add you.

**Comment by olabiniV2** [comment]
For now, I'll close this issue. Translation and pipelines for it will be looked at in detail a bit later.
