### ISSUE TITLE
Traducir al español

### ISSUE THREAD

**Issue by iapazmino** [coyim/coyim#248]
La traducción al español debe ser registrada en el archivo coyim/i18n/es_EC/LC_MESSAGES/coy.po

**Comment by tdruiva** [comment]
Si quieres, también puedes usar [esa plataforma](https://translate.zanata.org/zanata/project/view/coyim)
Solo necesito añandir el user :wink:

**Comment by felipe-** [comment]
Necesito permisos para editar el documento en el Zanata.

**Comment by caoquendo** [comment]
yo tambien puedo ayudar

**Comment by mscudero** [comment]
Ya comencé a trabajar en esto.

**Comment by njumbo** [comment]
a traducir se ha dicho ',:)

**Comment by tdruiva** [comment]
@felipe- @caoquendo @mscudero  @njumbo Tienen conta en Zanata? Cual user id?

**Comment by njumbo** [comment]
No, pero en este momento creo una :D

On Wed, Feb 24, 2016 at 10:12 AM, Tania Silva <notifications@github.com>
wrote:

> @felipe- <https://github.com/felipe-> @caoquendo
> <https://github.com/caoquendo> @mscudero <https://github.com/mscudero>
> @njumbo <https://github.com/njumbo> Tienen conta en Zanata? Cual user id?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twstrike/coyim/issues/248#issuecomment-188299624>.
>



-- 
*Nelson Jumbo**Developer*
Email                         njumbo@thoughtworks.com
Telephone+593 999 532 520
<http://www.thoughtworks.com>

**Comment by mscudero** [comment]
nop, pero ya voy a crear.

*María Fernanda Escudero L., PMP**Consultant & Operations Manager*
Emailmescudero@thoughtworks.com
Telephone+593 9 9 502 6468
Skypemaria.fernanda.escudero <mescudero@thoughtworks.com>
Twitter          @kaizen_fer <mescudero@thoughtworks.com>
[image: ThoughtWorks] <http://www.thoughtworks.com/>

**Comment by caoquendo** [comment]
@tdruiva es andres1905

**Comment by tdruiva** [comment]
Novedad, no necesita me enviar el id.
Antes de empezar a ayudar CoyIM, tienes que se añadir al proyecto de la lenguaje [aqui](https://translate.zanata.org/zanata/language/list)

**Comment by olabiniV2** [comment]
For now, I'll close this issue. Translation and pipelines for it will be looked at in detail a bit later.
