### ISSUE TITLE
Support additional field types in registration form

### ISSUE THREAD

**Issue by juniorz** [coyim/coyim#267]
The current account registration only renders text fields in the registration form.
We must come up with a safe way to handle CAPTCHA images.

**Comment by olabini** [comment]
Any update on this one?

**Comment by sacurio** [comment]
@claucece , the Captcha image is now showing in the account registration form:

![image](https://user-images.githubusercontent.com/1084317/61988200-c475c400-afe3-11e9-969b-cc03e62fb338.png)

**Comment by claucece** [comment]
Yes!! awesome work @sacurio ! I'll review over the weekend ;)

**Comment by olabiniV2** [comment]
Me and @sacurio reviewed this and with some small fixes, it looks good.
