### ISSUE TITLE
Allow adding a tag to verified fingerprints

### ISSUE THREAD

**Issue by xSmurf** [coyim/coyim#343]
As is possible in xmpp-client, it would useful to be able to add a "tag" to a fingerprint. Likewise it would be nice to display the first and last time a fingerprint was seen

**Comment by olabini** [comment]
Hm, I haven't seen the tag behavior. How does that work and what's the purpose?
Might there also be value in remembering when the fingerprint was verified?

**Comment by leif** [comment]
In `xmpp-client` I would often "verify" people but with suffix like "tofu" or "via-bob" added to their name. It would then tell me "alice@host is using a key that was verified for user@host-via-bob" or whatever. This was a sort of accidental feature, but I found it useful.

I have mixed feelings about remembering when it was verified; that would certainly be useful sometimes, but then again so would logging all chats.

The jackline client records how many times you've seen each key before (and maybe the first date? i forget), which is also nice but potentially harmful.

**Comment by olabini** [comment]
Interesting. Yeah, I'm also not necessarily happy about remembering times. But a mnemonic for the fingerprint sounds like a potentially useful thing.

**Comment by tcz001** [comment]
like this idea,

**Comment by olabini** [comment]
Any suggestions on where it would make sense to add tags like this? And where to display them?

**Comment by juniorz** [comment]
If we decide to fix #392 we could add the tag to the message telling the user the conversation went from unverified to verified, then adding the same message when starting a conversation with a verified peer would fix this completely.

Another option is to add a small "contact info toolbar" at the top of the transcript (the current `from@example.com <-> to@example.com` is also pretty confusing). But maybe this is another issue.

**Comment by olabini** [comment]
Ah, I see. Hmm.
