### ISSUE TITLE
Add in-band password change.

### ISSUE THREAD

**Issue by xSmurf** [coyim/coyim#344]
Users should be able to change password for their accounts. This is part of XEP-0077 and support on a majority of servers.

https://xmpp.org/extensions/xep-0077.html#registrar-formtypes-changepassword

**Comment by olabini** [comment]
That would be nice.

**Comment by Cris2760** [comment]
**User Stories**

**1.** As a user, I want have the option for change in the app my password, at any time for security reasons

Acceptance Criteria:
* When I have an active account, I click on change password option I should see a form with fields " Enter new password " and " Repeat the password" that must be match between them 

> Estimate time : 5d (21/6)

**2.** As a user, I would like to see if my password was changed successfully or if the process failed via UI

Acceptance Criteria:
* I should be able to see the message (success/fail) after I press the change button 
> Estimate time : 5d (21/6)

**Comment by claucece** [comment]
@sacurio @fraggerfox should we allow password changes only over tor, as in the registration?

**Comment by fraggerfox** [comment]
> 
> 
> @sacurio @fraggerfox should we allow password changes only over tor, as in the registration?

@claucece As of now, password changes can only happen once a connection has been established with the target server.

If my understanding is correct the current CoyIM forces existing accounts to connect via Tor is it not?

**Comment by claucece** [comment]
>If my understanding is correct the current CoyIM forces existing accounts to connect via Tor is it not? 

By default, it makes use Tor. But the user can change that if they want and they can ;) . The question remains: do we want to force users to change passwords only over tor?

Thanks!

**Comment by fraggerfox** [comment]
> > If my understanding is correct the current CoyIM forces existing accounts to connect via Tor is it not?
> 
> By default, it makes use Tor. But the user can change that if they want and they can ;) . The question remains: do we want to force users to change passwords only over tor?
> 
> Thanks!

Understood, if the user has the option to use (or not use) Tor when connecting (and not registering), we think it should be left to the discretion of the user to change password over the stream they have chosen to connect.

This way the natural flow of logic is not disrupted i.e. by default Tor is forced upon all registrations and connections going forward (unless the user decides not to use Tor for connecting), and whatever data is send out uses the setting the user has preferred to use.

However, it would be a good idea to display some sort of notification in the change password dialog box, to tell the user that they are trying to change their password over a non-Tor connection.

What are your thoughts on this?

**Comment by claucece** [comment]
> However, it would be a good idea to display some sort of notification in the change password dialog box, to tell the user that they are trying to change their password over a non-Tor connection.

I agree! 

So, yeah.. let's do so ;)

**Comment by sacurio** [comment]
![coyim-password-empty](https://user-images.githubusercontent.com/1084317/59953714-f3c66d80-9446-11e9-972e-c78854673871.png)
Error message for empty passwords.

![coyim-passwords-not-match](https://user-images.githubusercontent.com/1084317/59953716-f3c66d80-9446-11e9-8d9b-d0a91abd3c28.png)
Error message for mismatching passwords.

![coyim-success-change-password](https://user-images.githubusercontent.com/1084317/59953717-f45f0400-9446-11e9-80f4-cb3702d697ce.png)
Dialog box message for successfully password change.

**Comment by claucece** [comment]
hey @sacurio ! awesome! as we discussed during the pairing, let's just not have the last window as a pop-up ;)

**Comment by sacurio** [comment]
Tks @claucece ! And now We're working in change the pop-up according our las discussion.

**Comment by claucece** [comment]
I just realized something now: when changing the password, we also need to change the configuration file... @sacurio @fraggerfox what do you think?

**Comment by fraggerfox** [comment]
@claucece what do you think should change in the configuration file?

**Comment by claucece** [comment]
The functionality pushed hangs out. This is the log:

```
Called from gui/account_details.go. Attempting password change.
[CoyIM] 2019/06/25 21:47:30 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:31: Skipping SRV lookup
[CoyIM] 2019/06/25 21:47:30 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:102: Connecting to 5rgdtlawqkcplz75.onion:5222
[CoyIM] 2019/06/25 21:47:39 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28: Starting TLS handshake
[CoyIM] 2019/06/25 21:47:40 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   SSL/TLS version: TLS 1.2
[CoyIM] 2019/06/25 21:47:40 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
```

After a while, it crashes.

**Comment by claucece** [comment]
> @claucece what do you think should change in the configuration file?

The password which is in it.

**Comment by fraggerfox** [comment]
> > @claucece what do you think should change in the configuration file?
> 
> The password which is in it.

This was mentioned as a TODO in commit c50ea67a6cb8f9fee975d7875d3deaa758c9e5bf and has been implemented in 9fc87cc39056703a45d9b7238e3a7380eaf5e3fa

As of now the cache is cleared and the config file is cleared when a successful password reset is done. But after that the new password is saved only if the user chooses to save during the re-login attempt.

**Comment by fraggerfox** [comment]
> The functionality pushed hangs out. This is the log:
> 
> ```
> Called from gui/account_details.go. Attempting password change.
> [CoyIM] 2019/06/25 21:47:30 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:31: Skipping SRV lookup
> [CoyIM] 2019/06/25 21:47:30 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:102: Connecting to 5rgdtlawqkcplz75.onion:5222
> [CoyIM] 2019/06/25 21:47:39 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28: Starting TLS handshake
> [CoyIM] 2019/06/25 21:47:40 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   SSL/TLS version: TLS 1.2
> [CoyIM] 2019/06/25 21:47:40 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> ```
> 
> After a while, it crashes.

Thanks for these logs, I shall look into it. Looks like it fails at the TLS handshake which is strange.

**Comment by fraggerfox** [comment]
> > The functionality pushed hangs out. This is the log:
> > ```
> > Called from gui/account_details.go. Attempting password change.
> > [CoyIM] 2019/06/25 21:47:30 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:31: Skipping SRV lookup
> > [CoyIM] 2019/06/25 21:47:30 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:102: Connecting to 5rgdtlawqkcplz75.onion:5222
> > [CoyIM] 2019/06/25 21:47:39 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28: Starting TLS handshake
> > [CoyIM] 2019/06/25 21:47:40 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   SSL/TLS version: TLS 1.2
> > [CoyIM] 2019/06/25 21:47:40 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> > ```
> > 
> > 
> > After a while, it crashes.
> 
> Thanks for these logs, I shall look into it. Looks like it fails at the TLS handshake which is strange.

Can you also run CoyIM over non Tor and see if it still hangs?

**Comment by claucece** [comment]
> Can you also run CoyIM over non Tor and see if it still hangs?

Sure. Same logs:

```
[CoyIM] 2019/06/26 01:07:09 /Users/sofia/go/src/github.com/coyim/coyim/gui/ui_reader.go:50: Loading definition from local file: "gui/definitions/ChangePassword.xml"
Called from gui/account_details.go. Attempting password change.
[CoyIM] 2019/06/26 01:07:14 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:40: Make SRV lookup to: jabber.otr.im
[CoyIM] 2019/06/26 01:07:15 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:102: Connecting to jabber.otr.im:5222
[CoyIM] 2019/06/26 01:07:15 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28: Starting TLS handshake
[CoyIM] 2019/06/26 01:07:16 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   SSL/TLS version: TLS 1.2
[CoyIM] 2019/06/26 01:07:16 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
```

And a screenshot:

<img width="924" alt="Screen Shot 2019-06-26 at 1 07 19 AM" src="https://user-images.githubusercontent.com/8270508/60139651-fc080b00-97ae-11e9-9153-05b0da4c231e.png">

It does not do anything after that.. just hangs.

**Comment by claucece** [comment]
> As of now the cache is cleared and the config file is cleared when a successful password reset is done. But after that the new password is saved only if the user chooses to save during the re-login attempt.

Mmm.. we should revisit that decision in the next meeting ;)

**Comment by fraggerfox** [comment]
> > As of now the cache is cleared and the config file is cleared when a successful password reset is done. But after that the new password is saved only if the user chooses to save during the re-login attempt.
> 
> Mmm.. we should revisit that decision in the next meeting ;)

Probably, let us see if this works for now. Also there is more tweaking needed to be done in the configuration file part, found a bug when I was testing out a scenario. And let us not jump the gun for now, baby steps at a time :)

**Comment by fraggerfox** [comment]
> > Can you also run CoyIM over non Tor and see if it still hangs?
> 
> Sure. Same logs:
> 
> ```
> [CoyIM] 2019/06/26 01:07:09 /Users/sofia/go/src/github.com/coyim/coyim/gui/ui_reader.go:50: Loading definition from local file: "gui/definitions/ChangePassword.xml"
> Called from gui/account_details.go. Attempting password change.
> [CoyIM] 2019/06/26 01:07:14 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:40: Make SRV lookup to: jabber.otr.im
> [CoyIM] 2019/06/26 01:07:15 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:102: Connecting to jabber.otr.im:5222
> [CoyIM] 2019/06/26 01:07:15 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28: Starting TLS handshake
> [CoyIM] 2019/06/26 01:07:16 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   SSL/TLS version: TLS 1.2
> [CoyIM] 2019/06/26 01:07:16 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> ```
> 
> And a screenshot:
> 
> <img alt="Screen Shot 2019-06-26 at 1 07 19 AM" width="924" src="https://user-images.githubusercontent.com/8270508/60139651-fc080b00-97ae-11e9-9153-05b0da4c231e.png">
> 
> It does not do anything after that.. just hangs.

Alright, this seems to be a Mac specific issue, we were able to do a successful password change on Linux, Windows and BSD OSes. I shall look into it once @sacurio brings is Mac to do this testing.

**Comment by fraggerfox** [comment]
> > > Can you also run CoyIM over non Tor and see if it still hangs?
> > 
> > 
> > Sure. Same logs:
> > ```
> > [CoyIM] 2019/06/26 01:07:09 /Users/sofia/go/src/github.com/coyim/coyim/gui/ui_reader.go:50: Loading definition from local file: "gui/definitions/ChangePassword.xml"
> > Called from gui/account_details.go. Attempting password change.
> > [CoyIM] 2019/06/26 01:07:14 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:40: Make SRV lookup to: jabber.otr.im
> > [CoyIM] 2019/06/26 01:07:15 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:102: Connecting to jabber.otr.im:5222
> > [CoyIM] 2019/06/26 01:07:15 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28: Starting TLS handshake
> > [CoyIM] 2019/06/26 01:07:16 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   SSL/TLS version: TLS 1.2
> > [CoyIM] 2019/06/26 01:07:16 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> > ```
> > 
> > 
> > And a screenshot:
> > <img alt="Screen Shot 2019-06-26 at 1 07 19 AM" width="924" src="https://user-images.githubusercontent.com/8270508/60139651-fc080b00-97ae-11e9-9153-05b0da4c231e.png">
> > It does not do anything after that.. just hangs.
> 
> Alright, this seems to be a Mac specific issue, we were able to do a successful password change on Linux, Windows and BSD OSes. I shall look into it once @sacurio brings is Mac to do this testing.

Was the compiler used go 1.11? All 3 other OSes ran binaries compiled with 1.12 if I am not wrong.

**Comment by sacurio** [comment]
> The functionality pushed hangs out. This is the log:
> 
> ```
> Called from gui/account_details.go. Attempting password change.
> [CoyIM] 2019/06/25 21:47:30 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:31: Skipping SRV lookup
> [CoyIM] 2019/06/25 21:47:30 /Users/sofia/go/src/github.com/coyim/coyim/xmpp/tcp.go:102: Connecting to 5rgdtlawqkcplz75.onion:5222
> [CoyIM] 2019/06/25 21:47:39 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28: Starting TLS handshake
> [CoyIM] 2019/06/25 21:47:40 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   SSL/TLS version: TLS 1.2
> [CoyIM] 2019/06/25 21:47:40 /Users/sofia/go/src/github.com/coyim/coyim/session/logger.go:28:   Cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> ```
> 
> After a while, it crashes.

Hi @claucece , @fraggerfox and I, did "change password" by running CoyIM in different platforms, included macOS, the results were successful. We have attached the screenshots with macOS tests.
**Note:** The build was made using Golang 1.12.

<img width="760" alt="Captura de Pantalla 2019-06-26 a la(s) 9 55 24" src="https://user-images.githubusercontent.com/1084317/60213568-65c4fb00-9829-11e9-94f8-dfb66916b76f.png">

CoyIM account without Tor.


<img width="706" alt="Captura de Pantalla 2019-06-26 a la(s) 9 57 32" src="https://user-images.githubusercontent.com/1084317/60213577-68bfeb80-9829-11e9-8b2d-deca1d8d9e58.png">

Changing password of CoyIM account without Tor.


<img width="753" alt="Captura de Pantalla 2019-06-26 a la(s) 9 58 32" src="https://user-images.githubusercontent.com/1084317/60213579-6b224580-9829-11e9-885e-f27cc6ed9556.png">

Successfully password changed CoyIM account without Tor.


<img width="769" alt="Captura de Pantalla 2019-06-26 a la(s) 9 59 13" src="https://user-images.githubusercontent.com/1084317/60213585-6d849f80-9829-11e9-8b46-eb5a88cefbf6.png">

CoyIM account with Tor.


<img width="704" alt="Captura de Pantalla 2019-06-26 a la(s) 10 00 26" src="https://user-images.githubusercontent.com/1084317/60213588-6fe6f980-9829-11e9-97ca-95dd80ad59b0.png">

Changing password of CoyIM account with Tor.


<img width="755" alt="Captura de Pantalla 2019-06-26 a la(s) 10 01 15" src="https://user-images.githubusercontent.com/1084317/60213687-a15fc500-9829-11e9-8bd5-020f30d2d810.png">

Successfully password changed CoyIM account with Tor.

**Comment by fraggerfox** [comment]
@sacurio thanks for the update.

@claucece , may be try compiling with Golang 1.12 and let us know if you still face the same issues?

**Comment by claucece** [comment]
Hey @fraggerfox @sacurio ! Updated to golang 12.. still the same issue.. it freezes completely the whole application.

**Comment by fraggerfox** [comment]
> Hey @fraggerfox @sacurio ! Updated to golang 12.. still the same issue.. it freezes completely the whole application.

How about a fresh instance of CoyIM pointing to a new config file? Not sure if this would help but wanted to eliminate fact may be multiple connected accounts (even though we did test this scenario with 2 - 3 accounts), might be the cause of the issue.

If the hard freeze + crash keeps repeating even after the above test, we may need a proper debug run to figure out what exactly is causing it and without a method to exactly replicate it beyond your system this is going to be tricker to isolate.

**Comment by claucece** [comment]
Hey.. it works now. But there is still a lot of problems:

The image is not shown:

<img width="365" alt="Screen Shot 2019-07-02 at 3 50 19 PM" src="https://user-images.githubusercontent.com/8270508/60518149-3870c500-9ce1-11e9-9f5f-6f1b13571757.png">

The account gets disconnected and then it hangs:

<img width="925" alt="Screen Shot 2019-07-02 at 3 50 36 PM" src="https://user-images.githubusercontent.com/8270508/60518224-5d653800-9ce1-11e9-83b4-73e28855fb2e.png">

**Comment by fraggerfox** [comment]
> Hey.. it works now. But there is still a lot of problems:
> 

Good to hear, How did you manage to make it work?

> The image is not shown:
> 

Yes, @sacurio and I need to work on the various minor issues with the UI / UX.

> The account gets disconnected and then it hangs:
> 

Hangs as in it is no longer responsive? It could be because the "password entry" on connect dialog box overshadows the "Changed successfully" dialog box. Which makes it look like it hangs, but otherwise it should not hang. Again another UI issue that @sacurio and I need to sort out. 

That being said, the account "disconnect" on successful password change is expected, since the SASL stream used by the account will no longer be valid once a password change happens and it would need to re-authenticate itself.

But good to hear the password change works :)

**Comment by sacurio** [comment]
> The image is not shown:
> 
Hey @claucece , the image was removed and now shows correctly.

**Comment by claucece** [comment]
Thanks @sacurio .. let's pair on it tomorrow as said, as well ;)

Let's pair @fraggerfox as well tomorrow, as said ;) Then we can answer the questions together!

Thanks!

**Comment by sacurio** [comment]
Hi @claucece , please can you build the last commit and test if the change password process is working fine and let us know if it is still hanging.

**Comment by claucece** [comment]
Hey!

I will like to know why the new changes were made. In the past, I said I was uncomfortable with the idea of opening a double stream and other things without being listened too.. so idk why the change? Can we take this decisions as the team we are?

Thanks!

**Comment by fraggerfox** [comment]
Yes, @olabini reviewed the code yesterday and suggested this approach. When asked for a rationale he said CoyIM's code base is built on the assumption that there is only one single stream open per account, even though it is not a XMPP  violation to open a second stream. And that there may be parts of code that assume there is only one stream.

Also when pointed out that the go routine listening to IQs send over once a connection expects numerical IDs and not alphanumeric like in the XEP 0077 examples, he confirmed that the numerical ID of IQs is fine and it won't violate any existing rules since there is no such requirement in XEP 0077.

That being said being "uncomfortable" is not an explanation good enough to warrant a decision change, and it was not that you were not being heard, but the explanation was not sufficient.

**Comment by claucece** [comment]
Hey!

Thanks @fraggerfox 

> That being said being "uncomfortable" is not an explanation good enough to warrant a decision change, and it was not that you were not being heard, but the explanation was not sufficient.

I did said the same as @olabini in a meeting. It is very worrisome that these decisions again are not made by the team, not consulted neither to me nor @Cris2760 . It will be nice to actually start to work as a team and listen to other people. 

Thanks!

**Comment by fraggerfox** [comment]
> I did said the same as @olabini in a meeting. It is very worrisome that these decisions again are not made by the team, not consulted neither to me nor @Cris2760 . It will be nice to actually start to work as a team and listen to other people.
> 
> Thanks!

The aim of the change is to see if you are still able reproduce the hang / crash when you do a change password. That is why the old path way still exists, since it is not a "decision" to make an architectural change without consulting others. 

Because if you are still able to replicate the bug, then we need to sit down and look deeper into what exactly is happening at your end. Since I am put in charge of finding out why it does not work in your situation, I took the decision to have an alternative path way for you to test after discussing the issue with @olabini 

Please do note that this is not a permanent change or a decision taken without the discussion with team, but a way to find out if things still work at your end, once we have the findings, we can discuss today during our pair programming session, what exactly needs to be done with the current state of code.

**Comment by claucece** [comment]
Hey!

> Because if you are still able to replicate the bug, then we need to sit down and look deeper into what exactly is happening at your end. Since I am put in charge of finding out why it does not work in your situation, I took the decision to have an alternative path way for you to test after discussing the issue with @olabini

I don't see why this is related to the crash/bug I have. As far as I know, you don't have the logs of it, you can't reproduce it, so why do you think so?

I also fail to see why Ola was consulted, why is he repeatedly mentioned in this thread, as it was his decision to be way from work for a while, so, as team, that is something ought to be respected. 

> Please do note that this is not a permanent change or a decision taken without the discussion with team, but a way to find out if things still work at your end, once we have the findings, we can discuss today during our pair programming session, what exactly needs to be done with the current state of code.

The aim of the pair programming session was precisely to talk about these things, as it was decided by the team in the meeting. I think we ought to respect decisions taken by teams and team members, and to start listening to others in a respectful manner.

My two cents.

Thanks!

**Comment by fraggerfox** [comment]
> 
> 
> Hey!
> 
> > Because if you are still able to replicate the bug, then we need to sit down and look deeper into what exactly is happening at your end. Since I am put in charge of finding out why it does not work in your situation, I took the decision to have an alternative path way for you to test after discussing the issue with @olabini
> 
> I don't see why this is related to the crash/bug I have. As far as I know, you don't have the logs of it, you can't reproduce it, so why do you think so?
> 

Neither do I, Ola said it could be a possible issue and suggested trying out the alternative way to eliminate it as a possible cause.

> I also fail to see why Ola was consulted, why is he repeatedly mentioned in this thread, as it was his decision to be way from work for a while, so, as team, that is something ought to be respected.
> 

Ola was not consulted, he actually came to me and asked me about it when I was going through the code yesterday trying to figure out what could possibly be the issue, based on the log outputs I could see from the screenshot you shared.

I respect his decision to stay away from work and I have not initiated any engagements from my end.

> > Please do note that this is not a permanent change or a decision taken without the discussion with team, but a way to find out if things still work at your end, once we have the findings, we can discuss today during our pair programming session, what exactly needs to be done with the current state of code.
> 
> The aim of the pair programming session was precisely to talk about these things, as it was decided by the team in the meeting. I think we ought to respect decisions taken by teams and team members, and to start listening to others in a respectful manner.

That is exactly what is going to happen, nothing has changed, and I agree listening to others in a respectful manner goes both ways.

**Comment by claucece** [comment]
Hey!

I don't think this discussion is going anywhere, as usual ;) Let's talk about it in the meeting, as there is very worrisome things stated here. 

Thanks!

**Comment by fraggerfox** [comment]
> 
> 
> Hey!
> 
> I don't think this discussion is going anywhere, as usual ;) Let's talk about it in the meeting, as there is very worrisome things stated here.
> 
> Thanks!

Agreed :), let us discuss this during the pairing session and keep the morning stand up meeting short.

I do not think there is anything worrisome stated other than assuming things the wrong way.

**Comment by claucece** [comment]
Hey!

> Agreed :), let us discuss this during the pairing session and keep the morning stand up meeting short.

I will put a meeting after the standup.

> I do not think there is anything worrisome stated other than assuming things the wrong way.

As it has been said, that is something to discussed as a team.

Thanks!

**Comment by fraggerfox** [comment]
> 
> 
> Hey!
> 
> > Agreed :), let us discuss this during the pairing session and keep the morning stand up meeting short.
> 
> I will put a meeting after the standup.
> 

Sounds good.

> > I do not think there is anything worrisome stated other than assuming things the wrong way.
> 
> As it has been said, that is something to discussed as a team.
> 

Yup, I agree.

**Comment by claucece** [comment]
There is little TODOs missing for this issue:

@sacurio is working on giving the option of saving the new password to the user over the UI.
I am working on correctly testing and refactoring the code.

We might create a new smaller issue somewhat related to this one.

For your information @Cris2760 ;)

Thanks!

**Comment by Cris2760** [comment]
Thanks @claucece 

It will be great , if we create a new issue for this task, and included it as part of goals for CoyIM team.

**Comment by olabiniV2** [comment]
I reviewed this with @sacurio - we fixed a few smaller issues - including using i18n in all the right places, NEVER using markup when user defined text can be interpolated, and don't overwrite the users old password if they don't ask for saving the new message. With these changes, this issue is resolved from my perspective.
