### ISSUE TITLE
customizable unified view

### ISSUE THREAD

**Issue by cubi7** [coyim/coyim#353]
I would like to suggest the option of having a customizable layout in unified conversation mode. 

I currently use unified layout and work with my contact list on the right of my screen.

When a conversation happens, the window expands pushing the contact list towards the midle of the screen

Example,

no conversatoin
 `...................................... contact list (edge of screen)`

conversation happening.
`contact list - conversation - list of conversations (edge of screen)`

The admittedly superficial problem I have is when I close the conversations, the position of the contact list has now moved from right of screen to towards the center and I have to drag it back to right edge of screen.

after conversation closed

 `contact list  ...................................... (edge of screen)`

It would be great if possible to have the option to choose whether the contact list is on the left or right of unified layout as I believe that having it on the right side would keep the contact list at right edge of screen when closing conversations

Example

Left:
`contact list - conversation - list of conversations (edge of screen)`

Right:
`list of conversations - conversation - contact list (edge of screen)`

**Comment by olabini** [comment]
Thanks for the suggestions. That would definitely be good to have! I'm not sure we will get to implementing it though.

**Comment by sacurio** [comment]
@claucece , a first work in order to solve this issue was commited.
At the moment we're able to get and save the window coordinates in their x and y values, but there is an issue when we try to set the position of expanded conversation list view without a manual move before closing the conversation view, otherwise the window doesn't move to original position.

**Comment by sacurio** [comment]
@claucece , at the moment the main window position is correct after closing the conversation expanded view.

![353-1](https://user-images.githubusercontent.com/1084317/63129789-1cb63b00-bf7e-11e9-8b5a-c2726e0691e9.png)
**1. First step:** Open a conversation expanded view.

![353-2](https://user-images.githubusercontent.com/1084317/63129834-39527300-bf7e-11e9-9291-986fc17915f8.png)
**2. Second step:** Close the conversation expanded view.

![353-3](https://user-images.githubusercontent.com/1084317/63130036-d2818980-bf7e-11e9-9785-6181b81b2ece.png)
**3. Third step:** The main window return to the original position.

**Comment by claucece** [comment]
Perfect! Closing this! 

@cubi7 Let us know if it works for you ;)

**Comment by olabiniV2** [comment]
Reviewed together with @sacurio - it looks good. My only worry is what happens if a person moves the window after the unified view is opened, and then close the unified window. In that situation this new behavior is unintuitive. We will create a new issue to track it.
