### ISSUE TITLE
Support transferring an encrypted file or folder

### ISSUE THREAD

**Issue by olabini** [coyim/coyim#383]
This is part of properly implementing file transfer.

The current systems for transferring files don't allow for end-to-end encryption of the data. We should support using an implementation defined key to encrypt content. This would allow us to use the extra symmetric key from OTR to get real deniable encryption of data.

There are few different parts to this:
- Define new SI profiles for encrypted files and encrypted folders
  - These profiles should encrypt the metadata about the files
- Define a version of XEP-0065 that can encrypt the negotiation of StreamHost between the two peers
- Implement both sides of these profiles

**Comment by olabini** [comment]
This depends on all the other file transfer pieces being complete before starting work on it. Thus, we need:
- #381 
- #380 
- #379 
- #378

**Comment by olabiniV2** [comment]
So, the design for this feature doesn't seem to exist in any public repository - it is likely to be on my old computer, which I'm not sure when will be returned. 

Based on looking at the code, this is what needs to be done:
- [ ] Implement encryption of bytestream sending (this seems mostly done)
- [ ] Implement decryption of bytestream receiving
- [ ] Implement encryption of IBB sending
- [ ] Implement decryption of IBB sending

What is involved for sending is:
- Generate MAC and AES instances for the data and wrap the writers in it
- Write the MAC at the end of the send

What is involved for receiving is:
- Generate MAC and AES instances for the data and wrap readers
- Read the MAC
- Confirm the MAC
- Send back the MAC key

**Comment by olabiniV2** [comment]
It's not currently completely clear to me exactly how I was planning on sending back the MAC key (for additional deniability). I don't remember the plan, and it's not implemented yet.

**Comment by olabiniV2** [comment]
So, it turns out both IBB and bytestreams are bidirectional, so at the end, after verifying the MAC, we will simply send back the MAC key, either on the bytestream, or as an IQ.

**Comment by olabiniV2** [comment]
This last commit implements the rest of encrypted file transfer.
