### ISSUE TITLE
Consider adding ability to view roster when account is offline

### ISSUE THREAD

**Issue by entr0py** [coyim/coyim#397]
I employ multiple XMPP accounts to keep contacts isolated. If I can't remember which account a contact is assigned to, I'm currently required to log in to each account until I can locate the contact.

I don't have any idea what this feature would require technically. I imagine a local copy of each account roster would need to be kept and updated. I don't know if that goes against coyim's design philosophy.

In defense of this feature, the roster information could be kept in the encrypted config. Also, any attacker with access to coyim could log in to each account themselves.

Related bug: [Remove the account's contacts from roster after it disconnects. #39](https://github.com/twstrike/coyim/issues/39)

**Comment by olabini** [comment]
Hey

This is an interesting request. As far as I know the other XMPP clients do not do anything like this, but it should definitely be possible. However, there is a difference in saving it locally - an attacker with access might not have the capability to log in to the accounts, if the user has not saved the password, so your equivalence is not exactly correct.

**Comment by olabini** [comment]
After thinking about this for a while, I've come to the conclusion that for now, this is not a feature we will implement.
