### ISSUE TITLE
Mishandled angle brackets in message text

### ISSUE THREAD

**Issue by bfix** [coyim/coyim#411]
If an outgoing message contains an angle bracket pair "<...>" like a markup tag, only the text before the pair is received on the other end.

**Comment by olabini** [comment]
Hi,

I can't reproduce this. I sent `hallo <foo> bar` and received exactly the same thing on the other side. Can you specify what you're doing to make this behavior happen?

**Comment by bfix** [comment]
i happened reproducable in a conversation with a pidgin client on the other side.

**Comment by olabini** [comment]
This only happens when you have an OTR conversation going. Pidgin handles it correctly without OTR.

**Comment by olabini** [comment]
OK, so the behavior here is highly idiosyncratic and different inbetween different implementations. For example, Pidgin when sending will escape most html looking things, unless it's well formed style elements such as the "i" tag. However, if you have OTR turned on, EVERYTHING html looking will be escaped. Gajim seems to do the same thing.

It's not exactly clear what the right behavior here is.

Incidentally, I can't reproduce the behavior you are seeing. If I send `hello <foo> bar` Pidgin will show me `hello  bar` - obviously not great, but it's different from the behavior you mentioned.

**Comment by bfix** [comment]
sorry, i was unprecise in my first message, should have read: "... only the text *around* the pair is received..."

**Comment by bfix** [comment]
so escaping sgml text (at least in otr) is not an option for coyim?

**Comment by olabini** [comment]
Escaping HTML is absolutely possible, and indeed something we already do. The problem is _how_ we escape and _when_. And since Pidgin and Gajim and the others seem to do different things at different points, and that this differs depending on if an OTR conversation is active or not, it's a bit hard to figure out what behavior is the correct one.

**Comment by 0x27** [comment]
Ran into this same issue, kind of. When I send messages containing "<", everything after the "<" doesn't display Coyim side, but seems to display fine on my recipients side. Super annoying for pasting shell oneliners in chat to people...

**Comment by olabini** [comment]
The current behavior is that the angle brackets will be quoted as is, inside an OTR conversation. I'm fine with that. Hope that works for everyone.
