### ISSUE TITLE
Subscription request prompt steal focus

### ISSUE THREAD

**Issue by hfiguiere** [coyim/coyim#424]
Subscription request prompt steal focus by presenting a modal message box that comes above everything else. And since it focuses with the keyboard, it actually might cause acceptance by mistake.

This is related to issue #422. This is the UI problem.

IMHO the request should come as a notification, not a modal alert.

**Comment by hfiguiere** [comment]
I'm using 0.3.7_1

**Comment by hfiguiere** [comment]
And I run GNOME, in case you don't have the problem of focus grabbing.

**Comment by olabini** [comment]
Yeah, this is a problem. We need to come up with something nicer for this - although notifications are tricky too. People completely miss the Pidgin one all the time.

**Comment by hfiguiere** [comment]
But because pidgin use the old notification system that doesn't work well when one use GNOME 3 (gnome-shell) and still relies on the systray.

I already get better notification from Coyim.
