### ISSUE TITLE
Better integration with Tor

### ISSUE THREAD

**Issue by SweetVirginia** [coyim/coyim#433]
As an user I want to use CoyIM in its best settings, for that I must be using the Tor network so I can communicate privately. 

- If I don't have Tor installed and I don't know how to do it?
- If I have Tor installed, but it is not running? 

Here the basic flows we discussed previously:
[Tor integration.pdf](https://github.com/twstrike/coyim/files/1064925/Tor.integration.pdf)

 Thoughts?

**Comment by claucece** [comment]
Hi, Virginia, 

Thanks for this. 

I have made some modifications to the proposal. Basically:

1. It first checks if Tor is running. If not, it assumes not installed and asks for installation
2. Some texts. 

The problems that I see with this is that it has two windows popping out for the user to answer. 

Here is a [pdf](https://github.com/twstrike/coyim/files/1123116/Tor.integration.7.pdf) with the flow. It can be opened on illustrator.

Furthermore, I have made the code for this. You can see it and run it from 'torui' branch (06821464182ae1802bb3a41d5200b5f5be10b0d5, for example). 

What is still missing from your proposal:
1. Check that Tor is running. 

:)

**Comment by claucece** [comment]
UPDATE: 
It now successfully checks for Tor.

**Comment by claucece** [comment]
Hi, Virgina!

This is basically done. 

Here a [tor12.pdf](https://github.com/twstrike/coyim/files/1275523/tor12.pdf) with the flow and how it looks. 

Tell me if you have other recommendations, things to change. 

Thanks

**Comment by baimafeima** [comment]
My specific use case would be to use coyim in China. Access to the Tor network is blocked due to DPI inspection and it would be necessary to obfuscate traffic. Do you currently have any traffic obfuscation techniques implemented? Would you strive for making this to work OOTB?

**Comment by claucece** [comment]
Closing this by d08e434d524fc362df8dec7a0541718de9574c90. Can be reopen if it needs something else.
