### ISSUE TITLE
Right-clicking Mac icon doesn't reveal windows

### ISSUE THREAD

**Issue by natalieesk** [coyim/coyim#435]
If you have multiple windows open, when right-clicking on the Coy icon, you can't see a list of the open windows. To access them you would need to click on "show all windows"

**Comment by olabiniV2** [comment]
This is sorted out in the last commit, by setting a WindowMenu for OS X. Sadly, we are currently not deleting windows, so it will be a bit confusing to people - but I think we should refactor the code to destroy windows when we close them and recreate them afterwards. A different issue will be created to track this.
