### ISSUE TITLE
Hot keys get in the way for unified conversations

### ISSUE THREAD

**Issue by iapazmino** [coyim/coyim#444]
When you set conversations to be unified in a single window shortcuts for copy (Ctrl+C), paste (Ctrl+V), etc., activate menu functions instead of actually doing what is expected.

**Comment by claucece** [comment]
On MAC, you use cmd, so the  problem does not happen. I remember @iapazmino finding this on his ubuntu.

**Comment by olabini** [comment]
Hm, ok. I'll see if I can find the problem.
