### ISSUE TITLE
Search Bar (Ctrl+F) does not search nicknames

### ISSUE THREAD

**Issue by claucece** [coyim/coyim#446]
Currently, the search Bar (shown by Ctrl+F) only searches by account (i.e, bla@jabber.cryptoparty.is) but not by nickname. It should also search by nickname.

**Comment by juniorz** [comment]
Also the search will use the default `GtkTreeViewSearchEqualFunc` on the tree view.

It would be nice to make it more flexible. Searching for `ola` should match `ola@gmail.com` and also `paola@gmail.com`. This is also helpful to searching for contacts on certain servers.

**Comment by juniorz** [comment]
Look at:
- gtk_tree_view_set_search_equal_func ()
- g_str_match_string()

**Comment by tdruiva** [comment]
Tips: 
 - Ctrl+g: next result (key arrow down)
 - Ctrl+G: previous result (key arrow down)

**Comment by claucece** [comment]
Currently, search bar is also unable to search for contacts with '_' on them.  It will search 'sofi' but not 'sofi_celi' on sofi_celi@jabber.cryptoparty.is.
