### ISSUE TITLE
Verify migration to coyim organization

### ISSUE THREAD

**Issue by juniorz** [coyim/coyim#447]
- [x] Setup travis on the new org.
- [x] Remove references to `twstrike`
  ```
  $ git rev-parse HEAD
  475676422ee22e07870fae8c716fb988d11fd25d
  $ ack twstrike | wc -l
  692
  ```
- [ ] Update appveyor and make sure windows build works.
- [ ] Update bintray and make sure dmg works.
- [x] Double check github renaming "just works".

**Comment by juniorz** [comment]
I can't assign this issue to myself. Is there something missing to be configured on this repo/org?
cc/ @olabini

**Comment by olabini** [comment]
Try now.

**Comment by juniorz** [comment]
Travis: http://travis-ci.org/coyim/coyim
Coveralls: https://coveralls.io/github/coyim/coyim
Bintray: https://bintray.com/coyim/coyim-bin

**Comment by juniorz** [comment]
We can verify the remaining of this when we release another version.
