### ISSUE TITLE
Extract xmpp pkg from coyim pkg

### ISSUE THREAD

**Issue by juniorz** [coyim/coyim#448]
Now that we have a separate organization for all things coyim related, what do people think about extracting the `xmpp` pkg from `coyim` pkg and putting it directly under `coyim` org?

**Comment by juniorz** [comment]
It should not be hard to do this and keep history: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by olabini** [comment]
I guess we could do that, but the question is how useful the xmpp package on its own would be - we would still need to vendor it in the coyim project to get controlled reproducibility.

**Comment by olabini** [comment]
Closing this for now.
