### ISSUE TITLE
Race condition and lock in xmpp tests

### ISSUE THREAD

**Issue by olabini** [coyim/coyim#449]
Sometimes when running tests, it hangs on the xmpp tests. This is the output when it finally gives up:

=== RUN   Test
SIGQUIT: quit
PC=0x45ecb1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xb4f450, 0x0, 0x0, 0x0, 0x7fff00000000, 0x42a8b6, 0x0, 0x0, 0x7fff8e60f3f8, 0x410f5b, ...)
	/home/olabini/src/go1.9/src/runtime/sys_linux_amd64.s:438 +0x21
runtime.futexsleep(0xb4f450, 0x7fff00000000, 0xffffffffffffffff)
	/home/olabini/src/go1.9/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0xb4f450)
	/home/olabini/src/go1.9/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
	/home/olabini/src/go1.9/src/runtime/proc.go:1670 +0xe5
runtime.findrunnable(0xc42002c000, 0x0)
	/home/olabini/src/go1.9/src/runtime/proc.go:2125 +0x4d2
runtime.schedule()
	/home/olabini/src/go1.9/src/runtime/proc.go:2245 +0x12c
runtime.park_m(0xc420001980)
	/home/olabini/src/go1.9/src/runtime/proc.go:2308 +0xb6
runtime.mcall(0x7fff8e60f590)
	/home/olabini/src/go1.9/src/runtime/asm_amd64.s:286 +0x5b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420148000, 0x8caec8, 0x4, 0x8ec648, 0x47d5f6)
	/home/olabini/src/go1.9/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc420148000)
	/home/olabini/src/go1.9/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc420148000, 0xc42005bd78)
	/home/olabini/src/go1.9/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4200fc4c0, 0xb44120, 0x1, 0x1, 0x10037010040bd8e)
	/home/olabini/src/go1.9/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42005bf18, 0x25)
	/home/olabini/src/go1.9/src/testing/testing.go:921 +0x111
main.main()
	github.com/coyim/coyim/xmpp/_test/_testmain.go:136 +0x1b2

goroutine 5 [chan receive]:
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*suiteRunner).runTest(0xc420356c00, 0xc42044c2a0, 0xc420437680)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:810 +0x55
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*suiteRunner).run(0xc420356c00, 0xb6e0f0)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:615 +0xfc
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.Run(0x8a87c0, 0xb6e0f0, 0xc420066d80, 0xc420440120)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/run.go:92 +0x4d
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.RunAll(0xc420066d80, 0x0)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/run.go:84 +0xa4
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.TestingT(0xc4201480f0)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/run.go:72 +0x386
github.com/coyim/coyim/xmpp.Test(0xc4201480f0)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/xmpp/xmpp_test.go:18 +0x2b
testing.tRunner(0xc4201480f0, 0x8ec648)
	/home/olabini/src/go1.9/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/home/olabini/src/go1.9/src/testing/testing.go:789 +0x2de

goroutine 197 [select]:
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc4204401b0)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:461 +0xff
created by github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*resultTracker).start
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:441 +0x3f

goroutine 199 [chan receive]:
github.com/coyim/coyim/xmpp.(*XMPPSuite).TestConnClose_sendsAStreamCloseTagWhenWeCloseFirst(0xb6e0f0, 0xc420437770)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/xmpp/xmpp_test.go:125 +0x607
reflect.Value.call(0x8a87c0, 0xb6e0f0, 0xa13, 0x8cade4, 0x4, 0xc420044f70, 0x1, 0x1, 0xb6f9c0, 0x8c2f00, ...)
	/home/olabini/src/go1.9/src/reflect/value.go:434 +0x906
reflect.Value.Call(0x8a87c0, 0xb6e0f0, 0xa13, 0xc4201ecf70, 0x1, 0x1, 0x0, 0xc4201ecf07, 0xc420172880)
	/home/olabini/src/go1.9/src/reflect/value.go:302 +0xa4
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc420437770)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:772 +0x588
github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1(0xc420356c00, 0xc420437770, 0xc42040f560)
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:666 +0x7c
created by github.com/coyim/coyim/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall
	/home/olabini/.gopkgs/coyim/src/github.com/coyim/coyim/vendor/gopkg.in/check.v1/check.go:663 +0x218

rax    0xca
rbx    0xb4f340
rcx    0x45ecb3
rdx    0x0
rdi    0xb4f450
rsi    0x0
rbp    0x7fff8e60f3c0
rsp    0x7fff8e60f378
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc420428b40
r13    0xc420428b48
r14    0xa9
r15    0xc420428b40
rip    0x45ecb1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/coyim/coyim/xmpp	600.004s
?   	github.com/coyim/coyim/xmpp/data	[no test files]
?   	github.com/coyim/coyim/xmpp/errors	[no test files]
?   	github.com/coyim/coyim/xmpp/interfaces	[no test files]
?   	github.com/coyim/coyim/xmpp/socks5	[no test files]

**Comment by olabini** [comment]
Just testing something...

**Comment by juniorz** [comment]
I can investigate: `github.com/coyim/coyim/xmpp/xmpp_test.go:18`

**Comment by olabini** [comment]
I haven't seen this for a long time - it seems to be gone.
