### ISSUE TITLE
Strip trailing slashes from HOME in config_test.go

### ISSUE THREAD

**Issue by varac** [coyim/coyim#460]
I'm testing coyim with [reprotest](https://packages.debian.org/sid/reprotest):

> reprotest builds the same source code twice in different environments, and then checks the binaries 
> produced by each build for differences. If any are found, then diffoscope (or if unavailable then diff) is 
> used to display them in detail for later analysis.

`reprotest` modifies the `$HOME` variable and apparently adds a `/` at the end, which is unusual but valid.
`config_test.go` fails on this:

```
=== RUN   Test

----------------------------------------------------------------------
FAIL: config_test.go:102: ConfigXMPPSuite.TestFindConfigFile

config_test.go:107:
    c.Assert(conf, Equals, os.Getenv("HOME")+"/.config/coyim/accounts.json")
... obtained string = "/tmp/autopkgtest.AbEKda/const_build_path/.config/coyim/accounts.json"
... expected string = "/tmp/autopkgtest.AbEKda/const_build_path//.config/coyim/accounts.json"

OOPS: 31 passed, 1 FAILED
--- FAIL: Test (1.86s)
FAIL
exit status 1
FAIL	github.com/twstrike/coyim/config	1.880s
```

It would be nice it `config_test.go` would tolerate trailing slashes.

**Comment by varac** [comment]
well, the trailing slash is a assumption from me, all I see is that the test break using `reprotest`.

**Comment by juniorz** [comment]
Nice! Using https://golang.org/pkg/path/filepath/#Join should fix this.

**Comment by varac** [comment]
@juniorz would you be able to quick fix this ? That would unblock me.

**Comment by varac** [comment]
it still breaks with the same error

I pushed my branch `reprotest` and created a PR (https://github.com/coyim/coyim/pull/461).

If you like to use it pls go ahead:

```
make create-image-buster
make reprotest-buster   
```

and then it will break witht the above error at the current moment.
