### ISSUE TITLE
Test_Dial_worksIfTheHandshakeSucceeds_Proposed fails building the debian package

### ISSUE THREAD

**Issue by varac** [coyim/coyim#462]
I'm using git-buildpackage on my debian branch (`gbp buildpackage --git-ignore-branch --git-builder="dpkg-buildpackage -rfakeroot -us -uc" --git-no-pristine-tar --git-upstream-tree=debian`) to build the package.
`ConnectionXMPPSuite.Test_Dial_worksIfTheHandshakeSucceeds_Proposed`  fail like this:

```
=== RUN   Test

----------------------------------------------------------------------
FAIL: connection_tls_handshake_test.go:61: ConnectionXMPPSuite.Test_Dial_worksIfTheHandshakeSucceeds_Proposed

connection_tls_handshake_test.go:104:
    //This is different on 1.6, 1.7 ("EOF") but does the error string really matter?
    //c.Assert(err.Error(), Equals, "tls: server's Finished message was incorrect")
    c.Assert(err.Error(), Equals, recordedErr.Error())
... obtained string = "tls: server's Finished message was incorrect"
... expected string = "x509: certificate signed by unknown authority"

OOPS: 135 passed, 1 FAILED
--- FAIL: Test (2.26s)
FAIL
FAIL	github.com/coyim/coyim/xmpp	2.268s
?   	github.com/coyim/coyim/xmpp/data	[no test files]
?   	github.com/coyim/coyim/xmpp/errors	[no test files]
?   	github.com/coyim/coyim/xmpp/interfaces	[no test files]
?   	github.com/coyim/coyim/xmpp/socks5	[no test files]
```

Is this maybe related to my go version (`go version go1.8.3 linux/amd64`) ?

**Comment by juniorz** [comment]
This was removed by c4c7bc337858ec7a4d4232668ebf1998540a84b9

**Comment by olabini** [comment]
@juniorz does that mean this bug is fixed?

**Comment by varac** [comment]
@juniorz I rebased my debian branch on top of current master, but now I get differnt test failures, see 
[gbp.log](https://github.com/coyim/coyim/files/1651697/gbp.log).
Should I open a differnt issue for those ?

**Comment by juniorz** [comment]
Yes, open another issue. These seem to be related to the account importing.
