### ISSUE TITLE
Sign all commits with GPG

### ISSUE THREAD

**Issue by baimafeima** [coyim/coyim#463]
I've noticed that not all of the commits were signed with a verified signature. It would be great and increase security and trust to have all contributors sign their commits with GPG: https://help.github.com/articles/signing-commits-with-gpg/

**Comment by varac** [comment]
@baimafeima Thx, this is indeed good to enforce. We could implement a pre-commit (or server-side post-push) hook that only allows signed commits.
I feature to only allow signed pull request would be awesome as well but afaik this doesn't exist in github, correct me if I'm wrong.
Gitlab wants to implement it (see [Add option to only allow GPG signed merge requests](https://gitlab.com/gitlab-org/gitlab-ee/issues/3737) but it's currently tagged for enterprise edition only :/

**Comment by olabini** [comment]
While I would prefer all commits to be signed with GPG, I would argue against enforcing it with hooks for now. Everyone on the team should definitely have things set up to allow for this, but for now I'd like to avoid enforcement - I personally don't feel it gives enough security benefit on a project of this size.
