### ISSUE TITLE
Peers that DENY a subscription request disappear from roster

### ISSUE THREAD

**Issue by juniorz** [coyim/coyim#465]
The output generated by the roster's `Dump info` menu item shows peers that are not displayed on the roster:

```
->   Peer{coyim_is_better@jabber.cryptoparty.is[ ()], subscription='none', status=''('') online=false, asked=false, pendingSubscribe='', belongsTo='1509733031568853371', resources=map[], lastResource=''}
->   Peer{i_hate_this@jabber.cryptoparty.is[ ()], subscription='none', status=''('') online=false, asked=false, pendingSubscribe='', belongsTo='1509733031568853371', resources=map[], lastResource=''}
```

They are peers I have requested to subscribe but have not received an answer. I cant see them, and I cant resend a subscription request (maybe trying to add them again?)

**Comment by olabini** [comment]
That's strange. I can see them, while waiting for them to show up. Are you sure you haven't turned of the setting for displaying them?

**Comment by juniorz** [comment]
Note their `subscription='none'`, `pendingSubscribe='' ` and `asked=false`, so `isNominallyVisible()` is `false`.

**Comment by juniorz** [comment]
But yes, the option is set. They appear on pidgin with a line "Not Authorized" below them.

**Comment by juniorz** [comment]
Reading RFC 3921 [1], this issue seems to be described by section "8.2.1.  Alternate Flow: Contact Declines Subscription Request". That is, the contact **has denied** my request.

1 - https://xmpp.org/rfcs/rfc3921.html

**Comment by juniorz** [comment]
The bug stands renamed: it is weird that there is a line with `name@server.com (waiting for approval)` that disappears when they denies the request.
