### ISSUE TITLE
Account manager keeps yourself in on your contact list.

### ISSUE THREAD

**Issue by juniorz** [coyim/coyim#466]
The output generated by the roster's `Dump info` menu item shows yourself as a peer. This probably happens because the server seems to send you a presence IQ when you change your presence status (TODO: add reference to where the RFC says this should happen).

Is there any good reason for keeping this behavior?

**Comment by olabini** [comment]
Personally I find this helpful, and it has helped in debugging several issues - I don't see any problems with keeping the behavior.

**Comment by juniorz** [comment]
LGTM
