### ISSUE TITLE
UI: Give the app a more 'native' look and feel

### ISSUE THREAD

**Issue by sammcj** [coyim/coyim#472]
At present, it looks a bit... I can't put my finger on it - _odd_ ?

e.g.

- The top bar, why is it this big themed bar rather than a native window element? 
  ![screen shot 2017-11-28 at 3 55 33 pm](https://user-images.githubusercontent.com/862951/33303065-ae8c88de-d454-11e7-8338-42107d0979df.jpg)

- I like the idea of having a single window with panes rather than lots of floating windows (like Adium / Pidgin) but the panes need to be resizeable and preferably themed in a way that leads the idea to the conversation while designating from the contacts list etc...

**Comment by tdemin** [comment]
> The top bar, why is it this big themed bar rather than a native window element?

Because the client-side decorations are native for GTK+ 3.

**Comment by Lyberta** [comment]
Surely there is a way to change the style? AFAIK MATE also uses GTK+ 3 and respects the user theme.

**Comment by jontayesp** [comment]
I agree, the UI looks pretty bad IMHO.

**Comment by olabini** [comment]
Hi,

So, the look is basic GTK - we aren't doing any changes to the native elements, so that standard GTK theming can change the behavior and look of the UI. In general, this is an approach we will continue with, since it allows people to control their own look and feel.
