### ISSUE TITLE
Correctly report client name and version

### ISSUE THREAD

**Issue by varac** [coyim/coyim#473]
Currently, the xmpp client / version information for coyim is not retrievable from other clients, see attached screenshot from gajim: 
![screenshot from 2017-11-29 15-39-49-5](https://user-images.githubusercontent.com/488213/33380534-c077de1e-d51b-11e7-8e33-8089131ea99a.png)

I.e. other clients report sth like this:

Client: Conversations 1.22
System: Android
I'd be fine to not reporting the system (OS) although this could be good to know when it comes to debugging, but it should report a meaningful CoyIM version at least.

**Comment by olabini** [comment]
Actually, that's on purpose. We want to avoid giving away any information that isn't absolutely necessary.
