### ISSUE TITLE
Review Account Registration

### ISSUE THREAD

**Issue by juniorz** [coyim/coyim#477]
We found multiple issues on the "New Account" dialog:

- "Back" button does not destroy the form after it is rendered.
- Sometimes, there's a "Timeout" error just before the "Certificate dialog" is shown.
- There are some servers that never connect or time out.

cc @claucece

**Comment by claucece** [comment]
See here: 

<img width="651" alt="screen shot 2017-11-30 at 11 06 30 pm" src="https://user-images.githubusercontent.com/8270508/33566357-bab1a7e6-d8ed-11e7-8d8b-8aa527db8889.png">

**Comment by sacurio** [comment]
@claucece , the XMPP server list was updated in the Account Registration form. Now just the active servers are showed.

**Comment by claucece** [comment]
Awesome @sacurio ! We have not found this happening:

```
Sometimes, there's a "Timeout" error just before the "Certificate dialog" is shown.
```

So, we are closing this.

**Comment by olabiniV2** [comment]
I have reviewed these changes with @sacurio and it looks good. We might want to offer some more servers in the list of options later, but I'll add a new issue for tracking that.
