### ISSUE TITLE
Show room description when listing rooms from service

### ISSUE THREAD

**Issue by giovaneliberato** [coyim/coyim#479]
### Goal of this issue
Query and display room description when listing rooms from a service. We need to query all rooms and then query the extended room info for each one in order to get the description.

### Known problems
Doing a sync for loop in all rooms to get the information may take too much time (2~3 minutes) depending on how many rooms the service has. (service `conference.riseup.net` was used in this test)

### Possible approaches
* Try to do async calls with goroutines (although the requests are made thought the same connection socket)
* Create a button or a tooltip that requests and shows the room description on demand
* Don't show the room description at all

### Reference
* https://xmpp.org/extensions/xep-0045.html#disco-roominfo

**Comment by olabiniV2** [comment]
This one is now deprecated, since we will make a new plan and issues for MUC.
