### ISSUE TITLE
Should we remove the CLI?

### ISSUE THREAD

**Issue by olabini** [coyim/coyim#483]
Opening this up for discussion. I have no insight in how many uses the CLI, or whether it's valuable to keep.

If we do want to keep it, there are definitely some work that needs to be done in how we interact with OTR etc.

**Comment by olabini** [comment]
No comments on this for a while. I'm inclined to remove it. Next time I'll review this ticket I'll remove the package, unless we receive comments to keep it.

**Comment by baimafeima** [comment]
I think usability for the greatest number of users is important and I'd rather see this project focus on less things but to do them well.
