### ISSUE TITLE
UX: prioritize buddy name in window title

### ISSUE THREAD

**Issue by mfc** [coyim/coyim#485]
when using coy im, imagine chatting with multiple buddies on an account (say, your "Alice Normal" account).

## expected behavior

buddy name is first name in window title, so for instance: `Bud Buddy <-> Alice Normal`.

## current behavior

your account is first name in window title, so for instance: `Alice Normal <-> Bud Buddy`. this means that if you have five coy im chat windows open, as well as other windows, most likely your window bar in your OS environment will read: `Alice Normal ....` `Alice Normal ....` `Alice Normal ....` `Alice Normal ....` `Alice Normal ....`, etc. which is not very useful for finding the conversations you would like.

obviously enabling all conversations in one window solves this. but this would be a useful tweak for the default configuration.

## suggested change

have buddy name first in window title of chat windows.

**Comment by olabini** [comment]
Fixed, thank you for the suggestion!
