### ISSUE TITLE
Build error with new golang-1.10 and gtk-3 font_button

### ISSUE THREAD

**Issue by ageis** [coyim/coyim#487]
Fresh checkout, latest dependencies. New Go 1.10 that was just released. All packages and libraries are from Debian amd64 dist 'buster' (testing-->nextstable)
```
# github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/gtk
cgo-gcc-prolog: In function ‘_cgo_255aad219b0e_Cfunc_gtk_font_button_get_font_name’:
cgo-gcc-prolog:5296:2: warning: ‘gtk_font_button_get_font_name’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/gtk-3.0/gtk/gtk.h:106:0,
                 from vendor/github.com/gotk3/gotk3/gtk/gtk.go:48:
/usr/include/gtk-3.0/gtk/gtkfontbutton.h:96:23: note: declared here
 const gchar *         gtk_font_button_get_font_name  (GtkFontButton *font_button);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: In function ‘_cgo_255aad219b0e_Cfunc_gtk_font_button_set_font_name’:
cgo-gcc-prolog:5364:2: warning: ‘gtk_font_button_set_font_name’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/gtk-3.0/gtk/gtk.h:106:0,
                 from vendor/github.com/gotk3/gotk3/gtk/gtk.go:48:
/usr/include/gtk-3.0/gtk/gtkfontbutton.h:98:23: note: declared here
 gboolean              gtk_font_button_set_font_name  (GtkFontButton *font_button,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I tried to set `-Wno-errors` and that didn't suppress this I guess?

**Comment by juniorz** [comment]
The issue seems to be just a deprecation warning. From GTK docs " gtk_font_button_get_font_name has been deprecated since version 3.22" and Debian buster seems to have version 3.22.28-1, if I am reading the package info correctly (here: https://packages.debian.org/source/buster/gtk+3.0).

It should be a harmless warning.

**Comment by ageis** [comment]
@juniorz thanks, would you remind instructing me how to suppress Go warnings from being failing errors? I can't find any good info on Google..

**Comment by juniorz** [comment]
You can try to invoke `go build -x -work` (see the `go help build`) to have a better understanding of why this is failing.

Also, keep in mind go1.10 also uses the new `CGO_CFLAGS_ALLOW` and some flags may have been ignored in your system due this change. Take a look at https://golang.org/cmd/cgo/. Note that if this is the problem, go1.8.7 and 1.9.4 should also be affected. https://github.com/golang/go/issues/23749 is also a relevant issue on this subject.

Let us know if you find anything interesting.

**Comment by ageis** [comment]
@juniorz Thanks for the info. You can close this. Just for an FYI, I had tremendous difficulty resolving Tor .onion addresses with Go's built-in resolver and had to use CGO_ENABLED or build_tags netgo: https://github.com/prometheus/blackbox_exporter/issues/264

**Comment by olabini** [comment]
@ageis - I'm not sure what causes you to have DNS resolver problems with Go built-in resolver. I'm using hidden services for all my XMPP servers and have never seen any problems at all.
