### ISSUE TITLE
OMEMO support

### ISSUE THREAD

**Issue by knoy** [coyim/coyim#495]
OTR is unreliable, synchronous and works poorly on a mobile connection. OMEMO has effectively supercede OTR as the defacto opensource encryption standard. OMEMO support for coy.im would be a great benefit to the XMPP ecosystem

**Comment by olabini** [comment]
Hi, thanks for your suggestion. However, the CoyIM development team disagrees with your assertions, and we have no plan of supporting OMEMO.
For future reference, there are a number of issues opened about OMEMO in the past, where this is explained. For example: #233 #421 #199
