### ISSUE TITLE
I have a problem about registration

### ISSUE THREAD

**Issue by s3pt3mb3r** [coyim/coyim#496]
![image](https://user-images.githubusercontent.com/33578715/41792735-6cefa1c4-768c-11e8-8530-46a1fe850e16.png)

This is screen shot of registration window.
When I fill in the server name and click Next, coy will crash.

**Comment by olabini** [comment]
We need a little bit more information for us to be able to debug this. What does it say when crashing? Any output from the command line? What operating system?

**Comment by olabini** [comment]
Ah, it turns out this issue is a duplicate of #438 and has been fixed on trunk.

**Comment by grrrrr** [comment]
@olabini  any plans for a bug fix release? This ticket (#496) was submitted just short of a year after the issue was fixed in #438
