### ISSUE TITLE
GitLab

### ISSUE THREAD

**Issue by baimafeima** [coyim/coyim#499]
What do you think about moving the repository to GitLab? GitHub is closed-source, owned by Microsoft and generally less trustworthy than GitLab.

**Comment by sergeevabc** [comment]
“Generally less trustworthy”, how so?
Some security breach happened or it’s just “oh, Microsoft is beyond now, abandon the ship”?

**Comment by baimafeima** [comment]
Less trustworthy for the simple reason of Microsoft's embrace and extinguish strategy and attitude towards open source and the very fact that GitHub itself is not open source.

**Comment by olabini** [comment]
While there are good reasons to migrate to Gitlab at some point, it's not something that is high on our priority list. The collaboration features of Github is still significantly better than Gitlabs, and the work of moving to a new platform is simply not warranted at this time.
