### ISSUE TITLE
Add some screenshots to README or the website

### ISSUE THREAD

**Issue by alexara** [coyim/coyim#500]
This would help much to get a first impression. :-)

**Comment by claucece** [comment]
We have some screenshots in the website: https://coy.im/how-to-use/ .. but we can definitely make them better.. what do you think is mostly needed?

**Comment by alexara** [comment]
> We have some screenshots in the website: https://coy.im/how-to-use/ 

Oh, I had overlooked that particular page! :)

> what do you think is mostly needed?

Looking through the eye of a potential user or collaborator, I would be interested to see how the app looks like in a typical everyday use, before I start to consider downloading it.

That is why I expected to find a screenshot at least on https://coy.im/what-is-coyim/ and maby also at the GitHub README page.

Kind Regards

**Comment by baimafeima** [comment]
Any chance to get a new release out soon? The last one is over a year old.

**Comment by olabini** [comment]
@claucece - do you think you would have the possibility of adding a few to the README?

**Comment by claucece** [comment]
@olabini yes! I actually was thinking on doing so. Also, some of the screens have changed. So, if we do a new release, we have to change them to.

**Comment by olabini** [comment]
Perfect, that would be fantastic (you mean changing them on the website, right?)

**Comment by claucece** [comment]
Yes :)

**Comment by claucece** [comment]
Images have been changed on the website :)

**Comment by olabini** [comment]
Great, that's awesome! Will you be able to put some images in the README too?

**Comment by claucece** [comment]
Yes! I was just thinking how to make them look nice.. let's see.

**Comment by olabini** [comment]
This was finished in the last few commits.
