### ISSUE TITLE
Coy.IM website down?

### ISSUE THREAD

**Issue by TNTBOMBOM** [coyim/coyim#501]
im trying to access:

https://coy.im/

but its not working. 

Hope someone can fix that

**Comment by claucece** [comment]
It's up now. If still down, let me know @TNTBOMBOM

**Comment by TNTBOMBOM** [comment]
@claucece can check again please. its down again

**Comment by claucece** [comment]
I see it up. Checking in http://www.isitdownrightnow.com , it says: 'Coy.im is UP and reachable by us'

**Comment by lrq3000** [comment]
Seems down now...

**Comment by lrq3000** [comment]
Seems down for good now, it's reachable but it's a blank page with just the string "Staging of Coy.im"

**Comment by TNTBOMBOM** [comment]
just checked its working , but the issue coyim itself (as an app) is 
gone (you can check issues to know that).

So until the main developer released or new developer jump in well CoyIM 
is sadly dead.

Stephen Karl Larroque:
> Seems down for good now, it's reachable but it's a blank page with just the string "Staging of Coy.im"
>
