### ISSUE TITLE
Filter Spam messages by hiding messages from contacts you aren't subscribed to

### ISSUE THREAD

**Issue by kaie** [coyim/coyim#504]
It would be good to have a mechanism to prevent unwanted messages from being shown.
A simple approach is to hide messages from contacts that aren't in your contact list.

However, this approach will hide also messages from old contacts, which haven't talked to you in a while, and which you might have removed from your local contact list.

Therefore I think it's useful to make ignored messages discoverable.

I've submitted a pull request https://github.com/coyim/coyim/pull/503 with the following functionality:
- added "Ignore senders not in contact list" checkbox to global preferences UI, off by default
- if the user enables the new preference, those messages are not shown
- after coyim ignores a message, a new display in the contact list window will be shown. It will contain the number of ignored messages, the account ID of the most recently ignored sender, and a button. If the button is pressed, a list of all ignored contacts is displayed. This list isn't stored anywhere, it will be forgotten when coyim is closed.

**Comment by olabini** [comment]
Thank you for this work!

So, I've looked at the PR now. I'm a bit confused by a few things - I've added specific comments to the PR about those. However, the big comment here is that I don't actually think this solution to the problem is the right solution. Instead, I think the right solution is what is outlined in #422 - implementing privacy lists.

**Comment by olabini** [comment]
Actually no. Privacy Lists allow you to control contact requests, but it also allow you to control who you can receive messages from. Take a look at XEP-0016.

**Comment by kaie** [comment]
XEP-0016 says it has been deprecated. XEP-0191 says, that privacy lists from XEP-0016 is not widely implemented in servers. If server support is required for blocking that uses the privacy lists approach, then I don't see how XEP-0016 can be used to achieve the suggested enhancement.

Although XEP-0191 describes itself as a replacement (for XEP-0016), it focuses on specific JIDs, and apparently doesn't help for blocking unknown contacts.

Is there any XEP, which hasn't been declared obsolete, which doesn't require servers to implement new functionality, and which describes how messages could be filtered?

**Comment by olabini** [comment]
So yes, you're right that 191 can not serve this purpose, sadly. And while 16 is deprecated, it's the main way of implementing this functionality. Both Prosody and Ejabberd has had implementations of Privacy Lists for a long time, so I'm not sure where the comment in 191 comes from, honestly.

Fundamentally, for CoyIM I'm more interested in doing the right solution, irrespective of deprecation (we have implemented some other deprecated XEPs). Filtering spam messages locally, when the server can do it, is simply the wrong thing to do, in my opinion.
