### ISSUE TITLE
CoyIM Debian package has issues

### ISSUE THREAD

**Issue by TNTBOMBOM** [coyim/coyim#505]
The package needs someone to work on it in order to solve the issues mentioned here:

https://tracker.debian.org/pkg/coyim

**Comment by satta** [comment]
This is in reference to bug #916128 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916128) which is due to the following test failing at the moment:

```
FAIL: connection_policy_test.go:161: ConnectionPolicySuite.Test_buildProxyChain_Returns

connection_policy_test.go:181:
    c.Check(chain, DeepEquals, expectedProxy)
... obtained *socks.Dialer = &socks.Dialer{cmd:1, proxyNetwork:"tcp", proxyAddress:"proxy.local", ProxyDial:(func(context.Context, string, string) (net.Conn, error))(0x678b20), AuthMethods:[]socks.AuthMethod(nil), Authenticate:(func(context.Context, io.ReadWriter, socks.AuthMethod) error)(nil)}
... expected *socks.Dialer = &socks.Dialer{cmd:1, proxyNetwork:"tcp", proxyAddress:"proxy.local", ProxyDial:(func(context.Context, string, string) (net.Conn, error))(0x678b20), AuthMethods:[]socks.AuthMethod(nil), Authenticate:(func(context.Context, io.ReadWriter, socks.AuthMethod) error)(nil)}

OOPS: 31 passed, 1 FAILED
--- FAIL: Test (5.08s)
...
```
I can reproduce this with the dependencies currently in Debian unstable. Since in this Debian package passing the tests is required for the build to succeed, this is being treated as a build failure.
Any ideas? It looks like at least the string representations for the items to compare are the same.

**Comment by olabini** [comment]
Thanks for the report. I have pushed a fix to this now, and the tests work with the new version of the package.
Incidentally, these kinds of problems is exactly why vendoring is an important practice in golang land - we can't control dependencies and that things work properly, without controlling their versions... Oh well.

**Comment by olabini** [comment]
Is this different than #484 or the same - have you seen those issues as well or not?

**Comment by satta** [comment]
#484 seems to be something else. I don't observe this issue any more.
Will there be a new release soon or should I just patch 0.3.8 in Debian to include your changes? Anyway, many thanks for looking into this, much appreciated.

BTW I do indeed agree with your opinions about vendoring in Go (and Rust) land. Debian works differently though and things change a bit more slowly there.

**Comment by olabini** [comment]
OK great, thanks. I'll close that issue then.

About a release, I'm _hoping_ I can get a 0.3.9 out in second half of January. Would that be OK?

And yeah, about vendoring and dependencies - this is tricky stuff and evolving the approach will have to take time.
