### ISSUE TITLE
Allow Tor Stream Isolation 

### ISSUE THREAD

**Issue by TNTBOMBOM** [coyim/coyim#506]
I have searched in CoyIM settings to specify an specific IP and specific Port but couldn't find that anywhere. 

This feature is very important to anonymity by achieving the stream isolation. More you can read here:

https://www.whonix.org/wiki/Stream_Isolation

**Comment by olabini** [comment]
Hi,
I'm not sure exactly what you're looking for. However, CoyIM supports stream isolation already, through the standard way Tor supports stream isolation (with SOCKS5 username and password). In fact, that happens automatically with the tor-auto proxy support - but you can also do it manually using the proxy configuration settings for a connection.

**Comment by TNTBOMBOM** [comment]
i put the link explaining that but let me simplify: 

If there is CoyIM and Chromium and both using Tor, then both of them will be using the same circuit. And this is bad as it will co-relate the activity which leading to less anonymity.

**Comment by olabini** [comment]
Sorry, but you should read my answer more carefully. As I already told you, CoyIM uses stream isolation through SOCKS5 usernames/passwords. This means that CoyIM and Chromium will NOT use the same circuit.
