### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by koolfy** [coyim/coyim#507]
Similar to the apparently other translations in progress, I think I could help with a french translation.

I think the easiest for me would be to fork the project on my account, progressively translate each string then create a pull request that could be merged? Does that make sense?

I've never done any localization work before, or dealt with i18n stuff and tooling.
Is there a more clever way than just copying the English file over to a similarly named directory and replacing the strings? Am I missing the proper way of doing this?

Suggestions are welcome!

**Comment by olabiniV2** [comment]
While we get things under control, this will have to wait.
