### ISSUE TITLE
Notifications cannot show the '<' or '>' char

### ISSUE THREAD

**Issue by claucece** [coyim/coyim#508]
Notifications cannot show those chars. If for example the username is 'name <na@lol.com>', they will be shown as `name &lt;3na@lol.com&gt`.

**Comment by claucece** [comment]
Here the screenshots:

with `Show who sent the message`:

<img width="541" alt="Screen Shot 2019-07-08 at 3 57 03 PM" src="https://user-images.githubusercontent.com/8270508/60816098-3dc68780-a199-11e9-810d-8aec2983539a.png">


with `Show the message`

<img width="390" alt="Screen Shot 2019-07-08 at 3 57 35 PM" src="https://user-images.githubusercontent.com/8270508/60816112-47e88600-a199-11e9-8ef1-8ebf2e7f3fe4.png">

Tested on both OSX and Linux: same result.

**Comment by fraggerfox** [comment]
With the https://github.com/coyim/coyim/commit/4e271682690f7e3fd7c585f450feb90084fd4c5e commit, now EscapeAllHTMLTags() can parse "tags" properly so if the "<" and ">" are separated by spaces.

With only author info:
<img width="354" alt="only-author" src="https://user-images.githubusercontent.com/189939/60838992-b32e5a00-a191-11e9-9c5c-a0b4b8ead4a7.png">

With both author and message:
<img width="354" alt="show-message" src="https://user-images.githubusercontent.com/189939/60838993-b32e5a00-a191-11e9-9f4a-78e9eed1f761.png">

**Comment by claucece** [comment]
Nice, thanks! It still persists for `<user>`, as discussed

<img width="369" alt="Screen Shot 2019-07-09 at 2 21 42 AM" src="https://user-images.githubusercontent.com/8270508/60850605-5b730b80-a1f0-11e9-9223-3d1c6836cea9.png">
:

**Comment by fraggerfox** [comment]
With the above commit "<" and ">" won't be escaped, unless they are HTML tags.

<img width="354" alt="without-spaces-author-only" src="https://user-images.githubusercontent.com/189939/61135198-cc335580-a486-11e9-8806-a365b8d9aedd.png">

<img width="354" alt="without-spaces-with-message" src="https://user-images.githubusercontent.com/189939/61135200-cc335580-a486-11e9-889a-36f294e77fcc.png">

A list of known HTML tags are compared against to make this decision.
