### ISSUE TITLE
Make sure Windows build works for next release

### ISSUE THREAD

**Issue by olabini** [coyim/coyim#511]

**Comment by olabini** [comment]
This has now been fixed. There were some problems, the most major one moving to my appveyor account instead of Fan's, and then make things work with the new world stuff and changes that have happened the last 18 months.

**Comment by Neustradamus** [comment]
The last build does not start on Windows 7 x64.
-> https://coy.im/download/

**Comment by olabini** [comment]
Ouch, I'm sorry to hear that. What happens?

**Comment by xececibuku** [comment]
Nothing happens, it doesn't even launch.
Just downloaded CoyIM on windows, went to github to check issues. Made an account just to reply.

**Comment by olabini** [comment]
We are terribly sorry about that. We will investigate.

**Comment by olabini** [comment]
This problem has been fixed on trunk. We will shortly release a new version with this fix.

**Comment by Neustradamus** [comment]
Thanks @olabini for 0.3.10, it works!

**Comment by olabini** [comment]
Great!
