### ISSUE TITLE
RFCs and XEPs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#512]
It is possible to have a XEPs and RFCs support page with version?

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/gajimxepsupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by claucece** [comment]
This is actually a nice idea. We could add this to the website.

**Comment by olabini** [comment]
We already have a list of XEPs in the repo. Sure, we could add it to the website too.

**Comment by claucece** [comment]
Nice! I'll add something to the website. :)

**Comment by claucece** [comment]
Ok, I have added the supported XEPs to the website, and they can also be found here: https://github.com/coyim/coyim/blob/master/supported_xeps

**Comment by Neustradamus** [comment]
@claucece: It is not good!

Can you add the XEP versions and XMPP RFC numbers?
Example:
- XEP-0045 1.20.1: https://xmpp.org/extensions/xep-0045.html
- RFC6120: https://tools.ietf.org/html/rfc6120

**Comment by Neustradamus** [comment]
@claucece: Can you reopen this ticket?

**Comment by claucece** [comment]
> Can you add the XEP versions and XMPP RFC numbers?

Sorry, but this is something we are going to discuss as a team on having or not. And we will discuss on the appropriate website repo.

Thanks!

**Comment by Neustradamus** [comment]
@claucece, @olabiniV2: Can you reopen this ticket?

Version have not been added yet.

Thanks in advance.
