### ISSUE TITLE
XEP-0412: XMPP Compliance Suites 2019

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#513]
Please add support of https://xmpp.org/extensions/xep-0412.html

Which replace:
- XEP-0387: XMPP Compliance Suites 2018: https://xmpp.org/extensions/xep-0387.html
- XEP-0375: XMPP Compliance Suites 2016: https://xmpp.org/extensions/xep-0375.html
- XEP-0302: XMPP Compliance Suites 2012: https://xmpp.org/extensions/xep-0302.html
- XEP-0270: XMPP Compliance Suites 2010: https://xmpp.org/extensions/xep-0270.html
- XEP-0242: XMPP Compliance Suites 2009: https://xmpp.org/extensions/xep-0242.html

**Comment by claucece** [comment]
I see that xep-0412 is under consideration until 29/02/2019. Let's see the result of it.

**Comment by olabini** [comment]
I'm not super stressed about this either, since CoyIM is not a standard messaging client.

**Comment by Neustradamus** [comment]
A bad point.
