### ISSUE TITLE
XEP-0184: Message Delivery Receipts

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#514]
Can you add the XEP-0184: Message Delivery Receipts support:
- http://xmpp.org/extensions/xep-0184.html

**Comment by claucece** [comment]
I see that this is a draft standard still... @olabini do you think it is worth?

**Comment by olabini** [comment]
Actually, I really don't want this in CoyIM - it's the kind of feature that reveals more about what's going on on the people's computer.

**Comment by Neustradamus** [comment]
But you can add the function like other XMPP clients (with option to enable or disable)

**Comment by claucece** [comment]
I agree with @olabini . And also, the idea of CoyIM is to be secure by default; without the need of people of configuring, disabling things...

**Comment by Neustradamus** [comment]
It is in XEP-0412...

**Comment by claucece** [comment]
Just out of curiosity, why is the acknowledgment needed? This does not seem like a nice property to work with Tor... just guessing, here.

**Comment by olabini** [comment]
We are not necessarily a general purpose messaging client. We want to avoid adding things that are not absolutely necessary, since this adds complexity, and bugs and security holes hide in complexity. This is one of those features we probably will never add. Thanks for the suggestion!

**Comment by Neustradamus** [comment]
@olabiniV2: Have you changed about this XEP?

When the unencrypted or encrypted message is received by the XMPP client, we have a confirmation.

It is an option (not enabled by default if you want).

**Comment by olabiniV2** [comment]
No, I have not changed my mind on this.
