### ISSUE TITLE
Should we test with leaktest and ineffasign?

### ISSUE THREAD

**Issue by claucece** [coyim/coyim#515]
Here are the libraries:

- [ineffassign](https://github.com/gordonklaus/ineffassign)
- [leaktest](https://github.com/fortytw2/leaktest)

**Comment by olabini** [comment]
That could be nice to do. Not necessarily high priority, but still useful.

**Comment by claucece** [comment]
Ok, added `ineffassign`. Leaktest does not seem that necessary atm.
