### ISSUE TITLE
XEP-0368: SRV records for XMPP over TLS

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#518]
Can you add the XEP-0368: SRV records for XMPP over TLS support:
- https://xmpp.org/extensions/xep-0368.html

**Comment by olabini** [comment]
This looks nice to support. However, we would also have to implement Direct TLS for it to function - which might be bit larger, but still useful to have.

**Comment by Neustradamus** [comment]
@olabiniV2: Thanks!
