### ISSUE TITLE
RFC7590: Use of Transport Layer Security (TLS) in the Extensible Messaging and Presence Protocol (XMPP)

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#519]
Can you add the RFC7590: Use of Transport Layer Security (TLS) in the Extensible Messaging and Presence Protocol (XMPP) support:
- https://tools.ietf.org/html/rfc7590

**Comment by olabiniV2** [comment]
Actually, looking through it more carefully, it seems like we already are compliant with this RFC.
