### ISSUE TITLE
XEP-0191: Blocking Command

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#520]
Can you add the XEP-0191: Blocking Command support:
- https://xmpp.org/extensions/xep-0191.html

**Comment by olabini** [comment]
We have decided to not implement this XEP. However, Privacy Lists are something we are interested in implementing. #422

**Comment by Neustradamus** [comment]
@olabiniV2: Can you add this XEP in the same time than XEP-0016?

Some XMPP servers have XEP-0016 and some have XEP-0191.

**Comment by olabiniV2** [comment]
I think the decision on this stands. Privacy lists should be enough to cover the use cases - I don't really want to add too much complexity by implementing two different ways of doing the same thing.
