### ISSUE TITLE
UI bug: conversations list in single-window mode broken

### ISSUE THREAD

**Issue by ageis** [coyim/coyim#524]
This has been an issue for as long as I can remember. See the attached screenshots and the defect should be obvious (I have open conversations/IMs). I am not sure if it is because of my GTK theme or what, but other list/selection elements within the application display text correctly, so it must be a bug of some sort. Similar but not the same as #348.

![coyimbug](https://user-images.githubusercontent.com/1161532/54084967-56ab5300-42f5-11e9-8051-873198954995.png)
![coyimbug2](https://user-images.githubusercontent.com/1161532/54084968-57dc8000-42f5-11e9-91c7-a3673120bfe3.png)

**Comment by claucece** [comment]
Oh, interesting. I'll look up what is happening.

**Comment by claucece** [comment]
It does not show up for me in the dark theme I have. Can you let me know which theme you have? :)

**Comment by ageis** [comment]
@claucece I'm using Adwaita.

**Comment by ageis** [comment]
@claucece I just realized something, which is that it works with the official binary in Debian repositories, but not the one I self-built with Go. 
![coyimbug3](https://user-images.githubusercontent.com/1161532/54165109-915bdb00-441c-11e9-97ac-5c023ca81fcf.png)

**Comment by claucece** [comment]
@ageis can you try with the current commits of the repo?

**Comment by ageis** [comment]
@claucece I can confirm it's fixed in the master branch. Thanks and nice work!

**Comment by claucece** [comment]
Awesome! I'll close this.
