### ISSUE TITLE
All builds on github

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#525]
It is not possible to add all builds on github with the tag, release note, source code?
Example: https://github.com/github/hub/releases

In the same time, on the website, when I try to download, I have XSS detection...

**Comment by olabini** [comment]
Yes, it might be possible to do now. When we set up the build system, it was not possible to do this using the Github API - it might be possible now - that's why we use Bintray.

I'm not sure why you get XSS detection from Bintray - the download links lead directly to the downloads from there.

**Comment by Neustradamus** [comment]
Firefox + NoScript enabled, try it ^^

**Comment by olabiniV2** [comment]
Ah, I must have misunderstood this. All releases are already added to Github as part of our release process. I don't think we want to add for all _builds_, so this story is already done.
