### ISSUE TITLE
coyim misinterprets supported versions if query message suffix contains numbers

### ISSUE THREAD

**Issue by kaie** [coyim/coyim#529]
The OTR query message (e.g. ?OTRv2?) typically contains a suffix, intended for humans, such as "user a has requested OTR, your client doesn't support it".

If the remote client sends ?OTRv2? (only version 2), but the suffix contains the number 3, (e.g. if the chat username contains it), then coyim will incorrectly conclude that the other client supports version 3, and respond with a version 3 dhCommit message (which will be ignored by a version 2 only client).

Probably coyim performs a simple substring match for the number 3 on any parts of the query message. You probably should liimit the search to the initial part of the query message, and ignore the contents of the suffix.

**Comment by kaie** [comment]
Below is a test that illustrates the failure, which you could add to file conversation_test.go
```
func Test_receive_OTRQueryMsgV2RepliesWithDHCommitMessage(t *testing.T) {
	msg := []byte("?OTRv2? no otr support message 0123456789")
	c := newConversation(nil, fixtureRand())
	c.SetOurKeys([]PrivateKey{bobPrivateKey})
	c.Policies.add(allowV2 | allowV3)

	exp := messageWithHeader{
		0x00, 0x02, // protocol version
		msgTypeDHCommit,
	}

	_, enc, err := c.Receive(msg)
	assertEquals(t, err, nil)

	toSend, _ := c.decode(encodedMessage(enc[0]))

	assertDeepEquals(t, toSend[:3], exp)
}
```

**Comment by claucece** [comment]
Hey!

Thanks so much for reporting this. This is indeed a bug. I have fixed in the latest commit. I will answer to your pull request!

Thanks!
