### ISSUE TITLE
The Pinning policy information is difficult to understand

### ISSUE THREAD

**Issue by claucece** [coyim/coyim#530]
Currently, there is this information over the 'Account details' dialog: 

"The pinning policy governs whether we will consider saving information about certificates we have seen before, and how we will react in these cases. The none policy turns off this behavior. Deny will try to use the pins we already have, but will never connect to a server that has another certificate. The add policy will always add new pins - by itself, this is not so useful, but if you turn it off or change it to deny, you will have a list of pins that you can curate later. The add first and ask after policy will pin the first certificate we ever see, and then let the user know if we encounter other certifacates. The add first and deny policy does the same thing except it doesn't ever ask after the first certificate. Finally, the ask policy will always ask what to do when seeing certificates we haven't added."

While the information is correct, it is difficult to understand and to hard to actually read by an user. We should figure out a good UI/UX way of displaying it.

**Comment by sacurio** [comment]
@claucece , Santhosh and I reviewed the above text and came up with a revised alternative.

Do let us your thoughts / comments about proposed changes for the text to be displayed in "Account Details":

```
Certificate pinning policy

None:

Disable certificate pinning.

Deny:

Do not pin new certificates and only use the existing pinned certificates. In
case a certificate offered by the server is not found, the connection is
refused.

Always add:

Automatically pin new certificates from the server. A use case is when
connecting to multiple servers initially to store their certificate, then change
the option later to a more restricted one and curate them manually.

NOTE: This option must be used with caution.

Add the first, ask for the rest:

Automatically pin the first certificate we ever see and then for future
unpinned certificates we encounter we ask the user whether to accept or to
reject.

Add the first, deny the rest:

Automatically pin the first certificate we ever see and then for future
unpinned certificates we reject them all.

Always ask:

Ask the user every time we encounter a new unpinned certificate to accept or to
reject it.
```

**Comment by claucece** [comment]
Hey @fraggerfox and @sacurio .. it looks good to me! ;)

**Comment by claucece** [comment]
I can't assign you, @sacurio , to the issue. Can you check if you are part of the org now? An email should have reached you...

**Comment by fraggerfox** [comment]
> 
> 
> Hey @fraggerfox and @sacurio .. it looks good to me! ;)

Excellent, @sacurio and I shall work on implementing the changes in the UI tomorrow.

**Comment by fraggerfox** [comment]
Hello @claucece 

@sacurio and I worked on implementing the changes today and we have implemented the changes in our local copy of CoyIM.

Here is a screenshot for a side by side comparison of the current window (left) and the re-implemented window (right). Even though it is not visible in the screenshot, the text in the right window can be scrolled through.

![old_vs_new](https://user-images.githubusercontent.com/189939/58995307-523deb80-87b9-11e9-9aee-14a340a9a589.png)

The below file patches `gui/definitions/AccountDetails.xml` and you should be able to test out the changes yourself to see if everything is functional.

[AccountDetails.xml.patch.txt](https://github.com/coyim/coyim/files/3259304/AccountDetails.xml.patch.txt)

Let us know your thoughts on the changes.

If all things look good we can do the commit tomorrow.

**Comment by claucece** [comment]
Hey!

Looks nice! The only thing I will say:

'Certificate pinning policy' text: let's not have it underline. 

> The below file patches gui/definitions/AccountDetails.xml and you should be able to test out the changes yourself to see if everything is functional.
> AccountDetails.xml.patch.txt

Commit it directly and I will review in the commit.

Thanks!

**Comment by fraggerfox** [comment]
> 
> 
> Hey!
> 
> Looks nice! The only thing I will say:
> 
> 'Certificate pinning policy' text: let's not have it underline.
> 

We can remove the underline, shall we leave the text bold (as it is now)?

> > The below file patches gui/definitions/AccountDetails.xml and you should be able to test out the changes yourself to see if everything is functional.
> > AccountDetails.xml.patch.txt
> 
> Commit it directly and I will review in the commit.
> 

Alright, we shall do the commit tomorrow then.

> Thanks!

**Comment by claucece** [comment]
> We can remove the underline, shall we leave the text bold (as it is now)?

Yes! Bold is nice ;)

Thanks!

**Comment by sacurio** [comment]
@claucece , we have committed the changes. 

Can you review the changes and let us know if everything looks fine?

**Comment by olabiniV2** [comment]
I have reviewed this change with @sacurio and it looks good. I want some more text added, but we will create a new issue for that.+
