### ISSUE TITLE
version numbers are broken on macOS

### ISSUE THREAD

**Issue by core-code** [coyim/coyim#531]
i've downloaded version 0.3.11 but when selecting it in the macOS Finder, it reports itself as version 'dogfood' which is quite some nonsense.

your CFBundleVersion is 0.3 but should be 0.3.11
your CFBundleShortVersionString is 'doogfood' but should be 0.3.11

**Comment by claucece** [comment]
Hey, @core-code !

I see... I will change it, but unfortunately, we will have to wait for a new release for the total fix on this. Hope it is ok with you ;)

Thanks!

**Comment by core-code** [comment]
sure thanks!
