### ISSUE TITLE
CoyIM hangs when creating an account 

### ISSUE THREAD

**Issue by rbonfaz** [coyim/coyim#532]
CoyIM crashes when creating an account with jabber.ccc.de. To create an account with jabber.ccc.de you have to fill captcha. I don't know if this has something to do with the issue.
I am using CoyIM 3.11 in Debian 9.

I get this output after the crash:
```

panic: interface conversion: interface {} is *data.FixedFormField, not *data.TextFormField

goroutine 1 [running, locked to thread]:
github.com/coyim/coyim/gui.(*registrationForm).accepted(0xc4201899c0, 0xc420151040, 0xc420151068)
	/gopath/src/github.com/coyim/coyim/gui/registration.go:40 +0x3f9
github.com/coyim/coyim/gui.(*serverSelectionWindow).formSubmittedPage(0xc42007a2c0)
	/gopath/src/github.com/coyim/coyim/gui/registration.go:253 +0x47
github.com/coyim/coyim/gui.(*serverSelectionWindow).onPageChange(0xc42007a2c0, 0x1a575c0, 0xc4202866c0, 0x1a4f580, 0xc420286720)
	/gopath/src/github.com/coyim/coyim/gui/registration.go:287 +0x69
github.com/coyim/coyim/gui.(*serverSelectionWindow).(github.com/coyim/coyim/gui.onPageChange)-fm(0x1a575c0, 0xc4202866c0, 0x1a4f580, 0xc420286720)
	/gopath/src/github.com/coyim/coyim/gui/registration.go:296 +0x52
reflect.Value.call(0xcecdc0, 0xc4202ed880, 0x13, 0xe4a8e4, 0x4, 0xc42006bb60, 0x2, 0x2, 0x4, 0x5, ...)
	/root/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xcecdc0, 0xc4202ed880, 0x13, 0xc42006bb60, 0x2, 0x2, 0x2, 0x2, 0xc420151500)
	/root/go/src/reflect/value.go:302 +0xa4
github.com/coyim/coyim/vendor/github.com/coyim/gotk3adapter/gliba.FixupFunction.func4(0xe46e40, 0xc420196ac8, 0xdfd200, 0xc420196ad8)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/coyim/gotk3adapter/gliba/object.go:117 +0x113
reflect.Value.call(0xcefd00, 0xc42028b340, 0x13, 0xe4a8e4, 0x4, 0xc42006b380, 0x2, 0x2, 0xc420196ad8, 0xdfd200, ...)
	/root/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xcefd00, 0xc42028b340, 0x13, 0xc42006b380, 0x2, 0x2, 0xc420286650, 0x94, 0x0)
	/root/go/src/reflect/value.go:302 +0xa4
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.goMarshal(0x270e490, 0x0, 0xc400000002, 0x7fff821413d0, 0x7fff82141350, 0x0)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:216 +0x5af
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_fefed874382a_goMarshal(0x270e490, 0x0, 0x2, 0x7fff821413d0, 0x7fff82141350, 0x0)
	github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:4246 +0x5b
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x227f2a0, 0x0, 0x22a3340, 0x0)
	github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:1214 +0x4d
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0x227f2a0, 0x0, 0x22a3340, 0x473028)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:202 +0xab
github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc420198180, 0x1aaa268, 0x0, 0x0, 0x0)
	/gopath/src/github.com/coyim/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:202 +0x134
github.com/coyim/coyim/gui.(*gtkUI).Loop(0xc4201a4240)
	/gopath/src/github.com/coyim/coyim/gui/ui.go:411 +0xe9
main.runClient()
	/gopath/src/github.com/coyim/coyim/main.go:77 +0x1d1
main.main()
	/gopath/src/github.com/coyim/coyim/main.go:62 +0xaf

```

**Comment by claucece** [comment]
Hey!

> I am using CoyIM 3.11 in Debian 9.

Are you sure is this version?

I know there is a problem in Debian but it is of an older version (https://github.com/coyim/coyim/issues/527), which debian has not upgraded.

**Comment by rbonfaz** [comment]
I am using Debian, but not the package from the distribution. I downloaded the binary from the website:
https://coy.im/download/
I should clarify that the issue is not that CoyIM hangs, but it crashes. All the windows close at the same time.

**Comment by rbonfaz** [comment]
I just tested with Fedora 29 and Manjaro 18 and get the same issue. 

BTW, just jabber.otr.im iw working from the recommended server list. patchcord.be and xmpp.is are giving time out. From the test we did just a now.

**Comment by claucece** [comment]
Hey!

> BTW, just jabber.otr.im iw working from the recommended server list. patchcord.be and xmpp.is are giving time out. From the test we did just a now.

Yes.. that is a problem with the servers, which we cannot do that much. 

I will check this one `jabber.ccc.de`.. thanks!

**Comment by claucece** [comment]
The crash should be fixed, although it probably does not create an account.

**Comment by rbonfaz** [comment]
Just tested, it does not crashes. Thanks!

It would be nice to review the recommended server providers. One of the best things about CoyIM is that is really easy to create anonymous accounts. Having several providers is a nice future, maybe we should test another providers to put them in the recommended lists.

**Comment by claucece** [comment]
@rbonfaz ! Awesome! 

>It would be nice to review the recommended server providers. One of the best things about CoyIM is that is really easy to create anonymous accounts. Having several providers is a nice future, maybe we should test another providers to put them in the recommended lists.

For sure.. if you want, we can pair one day so I explain to you how the servers can be chosen.. what do you think?

**Comment by rbonfaz** [comment]
Good, so as it does not hangs any more I think we can close this ticket. I would love to help identify providers and test them. Let's meet.
