### ISSUE TITLE
Support of additional fields in change password form

### ISSUE THREAD

**Issue by claucece** [coyim/coyim#534]
This is related to this TODO `// TODO: server can also return a form requiring more information from the user. This should be rendered.` on the xmpp/registration.go file. Can be done in parallel to #267 as well.

**Comment by sacurio** [comment]
After trying to set a server to test this functionality we find it is not implemented in Prosody and doesn’t seem to be implemented in Ejabberd. We haven’t found public server that implement this. If this functionality is not implemented in the servers, it doesn’t make sense to implement in CoyIM at the moment.
