### ISSUE TITLE
My two issues with COYIM

### ISSUE THREAD

**Issue by ghost** [coyim/coyim#535]
First of all, love coy and everything it stands for as privacy software, but i have two problems, first being there's no real way to run it in the task tray, this also ties into the fact you can't close your first main window without it closing all chat windows.

If this is intentional please do say.

**Comment by claucece** [comment]
Hey!

Thanks so much for the comment around coy! <3

> first being there's no real way to run it in the task tray

Mmm.. which OS do you use?

> can't close your first main window without it closing all chat windows.

Yes, this is intentional. How is it problem for you?

Thanks!

**Comment by fwanky** [comment]
I use Arch Linux, and installed coy from the official repos. 
I can't really explain how it's a problem, I just don't really like having the main window open when i'm messaging people, I would rather be able to close the main window. I have also seen the option for having it all in one window but i'm not really a fan of that..
Another random thing, about tor-browser having to be open with coy, I like that you have to use tor, but is it not possible for it to run tor on it's own as a service without having to open the browser? Not really an issue, just wondering for the most part. Again, love the software.

**Comment by olabiniV2** [comment]
Hi, thanks for your comments!

- I have opened #551 to track the issue of minimizing to the tray. I definitely think that would be helpful
- About being able to close the main window, that is not something we are planning to support.
- About having to have Tor-browser open, you definitely don't need to do that. If you install tor as a service (something which is available on most operating systems), Coy will automatically use it, and you won't have to have Tor-browser open.
