### ISSUE TITLE
Receive and display previous discussion history when entering a room (7.2.13)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#558]
**Note:** Per each paragraph number, please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by Cris2760** [comment]
Ready for @olabini review

**Comment by olabiniV2** [comment]
OK, I've reviewed the code for this feature now, and overall it looks good. There are some things that need to be fixed - inlcuding some race conditions and some style issues, but as soon as that is done, this story can be marked as done and closed.
