### ISSUE TITLE
After entering a room, listing and updating the list of nick names in the room (7.2.2)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#561]
**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
Hi @olabiniV2, this issue is ready to close

**Comment by olabiniV2** [comment]
It seems to work. I'm not a huge fan of how the garbage collection is handled. If the problem is the lifetime of the builder, a better solution would be to just create the Model in code instead of using the builder for it... I'll keep it open for now.

**Comment by olabiniV2** [comment]
It also seems like not all affiliations are handled.

**Comment by sacurio** [comment]
> It seems to work. I'm not a huge fan of how the garbage collection is handled. If the problem is the lifetime of the builder, a better solution would be to just create the Model in code instead of using the builder for it... I'll keep it open for now.

We changed the model initialization through code instead of using the `builder`, but we had a little problem on trying to add the icon column, because the current columns types provided by `gtk3adpater` doesn't expose any specific type for `Pixbuf` and we need this for the occupant icon.

After we were looking around in how to solve this `Pixbuf` type problem, we noticed that exist an update in `gotk3` library that, among other things, exposes a method called `PixbufGetType()` necessary for us. https://github.com/gotk3/gotk3/blob/030ba00f1a888bf40d77b16a664e29f845d16d0a/gdk/pixbuf.go#L68 . We can do the library upgrade in the refactoring, if this sounds good for you.

**Comment by sacurio** [comment]
> It also seems like not all affiliations are handled.

Now (in 6797afad) all the affiliations are handled, but Member and None affiliations is not showed intentionally in order to avoid the visual overload in the occupant list. We could work properly in this when we will handle the occupant information.

**Comment by olabiniV2** [comment]
That's all fine. I just wanted to make sure all affiliations were actually handled - they won't necessarily be shown.

**Comment by olabiniV2** [comment]
> > It seems to work. I'm not a huge fan of how the garbage collection is handled. If the problem is the lifetime of the builder, a better solution would be to just create the Model in code instead of using the builder for it... I'll keep it open for now.
> 
> We changed the model initialization through code instead of using the `builder`, but we had a little problem on trying to add the icon column, because the current columns types provided by `gtk3adpater` doesn't expose any specific type for `Pixbuf` and we need this for the occupant icon.
> 
> After we were looking around in how to solve this `Pixbuf` type problem, we noticed that exist an update in `gotk3` library that, among other things, exposes a method called `PixbufGetType()` necessary for us. https://github.com/gotk3/gotk3/blob/030ba00f1a888bf40d77b16a664e29f845d16d0a/gdk/pixbuf.go#L68 . We can do the library upgrade in the refactoring, if this sounds good for you.

OK, sounds like a plan.

**Comment by peterpalau** [comment]
> It seems to work. I'm not a huge fan of how the garbage collection is handled. If the problem is the lifetime of the builder, a better solution would be to just create the Model in code instead of using the builder for it... I'll keep it open for now.

Done via 33066fd0b1169497decc1350f0b45115838e8df5.
