### ISSUE TITLE
Change the subject in a room, if allowed - but only display this option if the user has the capability (7.3, 8.1)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#565]
If the user is allowed to change the subject, the room view should show an option to change it. 

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
We found a little strange behaviour, so it comes back to `Doing` state

**Comment by azlancpool** [comment]
The strange behaviour was related to a code modification for a specific scenario used in the presentation (user test meeting) of another issue. So, it's ready for user testing

**Comment by peterpalau** [comment]
The issue is ready to be tested again.

**Comment by olabiniV2** [comment]
Looks good.
