### ISSUE TITLE
Kick a person in a room (8.2) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#570]
A moderator should be able to kick a person from a room, changing their role to "none". This functionality should be accessed from the user panel in the roster view. An optional reason should be possible to provide as well.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
A few things are pending to do

**Comment by azlancpool** [comment]
This issue should change the occupant roster panel when an occupant has been kicked, so it should come back to `Doing` state.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some things to fix.

**Comment by azlancpool** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK
