### ISSUE TITLE
Ban a person in a room (9.1) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#571]
An administrator or owner can ban a person from a room. For ease of use, we should only allow access to this functionality from inside the room view, for now. However, for banning a person that is not in the room, it should be possible to enter an arbitrary JID. If the user is in the room, the functionality should be possible to access from the user panel in the roster.

The XEP allows for manipulating lists of banned users in different ways, but for now we will not make this functionality available. Instead, we will simply allow an admin or owner to ban one single user.

An optional reason should be possible to provide as well.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by peterpalau** [comment]
Working on this issue, we realized is taking more than **small** work. For that reason, we are going to estimate as **medium** work.

**Comment by peterpalau** [comment]
The issue is ready to be tested by the users.

**Comment by Cris2760** [comment]
Blocked by #640

**Comment by azlancpool** [comment]
#640 is ready for user-test so, it could be unlocked

**Comment by peterpalau** [comment]
We need to fix some code review comments.

**Comment by olabiniV2** [comment]
Reviewed, OK

**Comment by azlancpool** [comment]
We must change the notifications colors based on the type of affiliation or role

**Comment by azlancpool** [comment]
The color of notifications was modified in ffffa4a6beacaa5f0cb5df3367ea46aeac5cd5e1. It's ready to user test

**Comment by Cris2760** [comment]
This issue is blocked by: #769

**Comment by azlancpool** [comment]
The issue #769 is in `user-test` state, so we can remove the `blocked` label

**Comment by olabiniV2** [comment]
OK
