### ISSUE TITLE
Grant ownership to a person that doesn't have it (10.3) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#573]
An owner can add owner privileges to another person, changing their affiliation to "owner". For now, for ease of development, we should give access to this functionality from the user panel in the roster. We should also consider how to do it for a user who is not actively in a room. For now, this could be a standalone dialog.

When adding owner privileges. you should be able to provide an optional reason for it.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
A small thing to fix.

**Comment by olabiniV2** [comment]
OK, looks good.
