### ISSUE TITLE
Find out who and how many people are in a room (without joining the room) and async populating the list of rooms with this information (6.5)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#577]
**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
We are actually already doing this, as much as possible.

**Comment by olabiniV2** [comment]
The only thing we are not doing is trying to discover the list of participants in the room, and showing that somewhere, but I don't think that's necessary functionality.

**Comment by peterpalau** [comment]
Yeah, I don't know if this can be useful for someone but, the thing that worries me is the fact that this feature exists for some reason. The only use that I think we can give it is to show a fancy room list with an indicator of the current number of occupants in each room. I don't know, I'm just speaking from my ignorance.
