### ISSUE TITLE
Being warned about the logging of content in a room when entering (7.2.12)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#583]
**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
Waiting on @rafaelbonifaz to investigate turning it on on a server, so we can test it.

**Comment by rafaelbonifaz** [comment]
You should be able to test it now.
