### ISSUE TITLE
Provide a password for entering a room (7.2.5)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#586]
Some rooms are password protected. For these rooms we should ask for a password when challenged.

**Note:**  Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by Cris2760** [comment]
Ready for @olabiniV2  review

**Comment by olabiniV2** [comment]
OK, there's a bunch of comments to fix. I'm moving this back.

**Comment by peterpalau** [comment]
Okay, all comments has been fixed, I'm going to move this to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, there are two small comments, but not enough to stop this from being finished. I think we can move this to done.
