### ISSUE TITLE
Deny entering a room where you are banned with an appropriate message (7.2.7)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#590]
If you are banned from a room, when trying to enter it you should be denied with a proper message.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by MauroVelasco** [comment]
Ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Good enough. There's a small language issue in one comment, but nothing major.

**Comment by olabiniV2** [comment]
OK

**Comment by peterpalau** [comment]
This issue is done and ready to be closed.

**Comment by peterpalau** [comment]
We were to fast closing this issue because there is a pending comment to fix, so I'm going to open it again to fix that comment.

**Comment by peterpalau** [comment]
No more comments about things to fix. The issue is ready to be closed.
