### ISSUE TITLE
Deny entering a room with max users with an appropriate message (7.2.9)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#591]
When you try to enter a room that is already full, you should be given an appropriate error message.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by peterpalau** [comment]
The issue is ready to be reviewed by @olabiniV2.

**Comment by olabiniV2** [comment]
Looks good.

**Comment by peterpalau** [comment]
The user tests are finished and the only recommendation was made so, the issue is done.
