### ISSUE TITLE
For each nick name, make it possible to see their real JID, if the information is available (7.2.2)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#593]
**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by Cris2760** [comment]
Ready for @olabiniV2  review

**Comment by olabiniV2** [comment]
OK, reviewed. There is definitely some code things that need to be improved.

**Comment by azlancpool** [comment]
@olabiniV2 this is ready for you review, all comments were done.

**Comment by olabiniV2** [comment]
OK, so I think there's one more thing to sort out - this question of hard-coding styles in various places. It would be good if we can fix that through this story.

**Comment by peterpalau** [comment]
> OK, so I think there's one more thing to sort out - this question of hard-coding styles in various places. It would be good if we can fix that through this story.

Okay, the styles-thing has been updated and, we have now a proper way for applying styles to MUC-related interfaces and components.

**Comment by peterpalau** [comment]
All pending comments has been fixed and this issue is ready to be reviewed, in order to close it.

**Comment by olabiniV2** [comment]
There are some new things to fix now...

**Comment by olabiniV2** [comment]
OK, there's some comments left to fix on the unified style thingy.

**Comment by peterpalau** [comment]
The comments has been fixed.

**Comment by olabiniV2** [comment]
OK, looks good.

**Comment by sacurio** [comment]
We're going to close this issue because all the comments has been fixed, the code review is done and user tests are finished.
