### ISSUE TITLE
Display notification when others leave the room (7.14)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#606]
**Note:**  Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by MauroVelasco** [comment]
After the weekly meeting we agree with add the timestamp info to 'username left room' text

**Comment by MauroVelasco** [comment]
text added

**Comment by MauroVelasco** [comment]
This issue is ready for review of @olabiniV2

**Comment by olabiniV2** [comment]
This seems to be alright. I am a bit unhappy about how updates to the roster is handled, but that should be resolved with the bigger refactoring we are planning. The current code doesn't seem to apply the timestamp when someone is leaving though, so I'll have to leave this open.
