### ISSUE TITLE
Remove yourself from the room when you get kicked, and display reason and person that kicked (8.2)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#609]
When you get kicked, this is because a moderator changed your role to "none". When this happens, you should be notified about it. When this happens, the room should be disabled. The notification should show you who kicked you, and what the optional reason is.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
OK
