### ISSUE TITLE
Grant voice to a person that doesn't have it (8.3) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#610]
A moderator should be able to give voice to a user that doesn't have it, by either changing their role to moderator or to participant. This functionality should be accessible from the user panel in the roster. It should be possible to provide an optional reason.

Note: Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
OK

**Comment by azlancpool** [comment]
This issue should be reopen because there are a  comment to do

**Comment by azlancpool** [comment]
It's ready to be reviewed

**Comment by azlancpool** [comment]
It's ready to be reviewed
