### ISSUE TITLE
Be notified when you get voice (8.3)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#613]
When your role changes from visitor to participant or moderator, you should be notified of this, and the possible reason for it - and who did it. This notification should probably happen in the room view, but outside the conversation view.

**Note:**  Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
OK
