### ISSUE TITLE
Revoke voice from someone (8.4) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#614]
A moderator should be able to change another moderator or participant into a visitor, thus making them unable to speak. This functionality should be accessible through the user panel in the roster. An optional reason should be possible to add.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
User test suggestions are ready, it's ready to be reviewed

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
Comments fixed, it's ready to be reviewed

**Comment by olabiniV2** [comment]
OK
