### ISSUE TITLE
Display notification when someone loses voice (8.4)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#616]
When someone changes the role of another person to being a visitor a notification of this should be shown in the conversation view. This notification should include who did it, what the new role of the user is, and the optional reason.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
Two issues were tagged in order to solve comments, but the commit bb982d5b785114741adf37305ff36f8fbb2ae267 couldn't be tagged again .
All comments were fixed and it's ready to be reviewed

**Comment by olabiniV2** [comment]
OK
