### ISSUE TITLE
Be notified when you lose voice (8.4)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#617]
When a moderator changes your role away from being a participant to a visitor, you should receive a notification of this. This should also result in the user interface stopping you from writing messages. The notification of this should be outside of the conversation view, and should tell you who did it, and the optional reason.

**Note:**  Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
OK
