### ISSUE TITLE
Display notification when someone gets banned (9.1)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#619]
When someone changes the affiliation of another person to being an outcast (being banned), a notification of this should be shown in the conversation view. This notification should include who did it, what the new affiliation of the user is, and the optional reason.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
OK
