### ISSUE TITLE
Remove yourself from the room when you get banned, and display reason and person that banned (9.1)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#620]
When you get banned, this is because an administrator or owner changed your affiliation to outcast. When this happens, you should be notified about it. If you are not currently in the room, a standalone notification should be displayed. If you're in the room, the room should be disabled. In both cases, the notification should show you who banned you, and what the optional reason is.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
OK, looks good.
