### ISSUE TITLE
Grant membership to a person that doesn't have it (9.3) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#621]
An administrator or owner can add membership to a person, changing their affiliation to "member". For now, for ease of development, we should give access to this functionality from the user panel in the roster. We should also consider how to do it for a user who is not actively in a room, since otherwise there doesn't exist a way to add members to a members-only room. For now, this could be a standalone dialog.

When revoking the membership, you should be able to provide an optional reason for it.The admin can grant membership to a user.

**Note:**  Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
It is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Looks fine to me.
