### ISSUE TITLE
Be notified of success or failure of the membership grant (9.3)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#622]
When you try to add the membership affiliation to another user, you should be notified if this succeeded or failed, and if it failed, why.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
Changes related with user-test suggestions was done in 80e286c1cb6336c499872c191b1048c9be7b8bb7

**Comment by olabiniV2** [comment]
Looks ok.
