### ISSUE TITLE
Display notification when someone gets to be a member (9.3)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#623]
When someone changes the affiliation of another person to being a member, a notification of this should be shown in the conversation view. This notification should include who did it, what the new affiliation of the user is, and the optional reason.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
It seems like some commits are mixing. The two referenced commits here are clearly not enough for this functionality, right?

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed

**Comment by olabiniV2** [comment]
Things to fix

**Comment by azlancpool** [comment]
All comments were fixed, it's ready to be reviewed

**Comment by olabiniV2** [comment]
Things to fix

**Comment by olabiniV2** [comment]
OK
