### ISSUE TITLE
Revoke membership to a member (9.4) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#625]
An administrator or owner can revoke the membership of a person, changing their affiliation to "none". For now, for ease of development, we should give access to this functionality from the user panel in the roster.

When revoking the membership, you should be able to provide an optional reason for it.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
ok, looks good.
