### ISSUE TITLE
Be notified when you are removed as member (9.4)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#628]
An administrator can change the affiliation of a user from member to "none". When this happens to you, you should be notified of it. Since this can happen both when you are inside a room, or when you are outside the room and don't have it open, this story involves the notification happening in both these cases. When not in the room, a standalone notification should be displayed, while when you're in the room, you will have the same behavior as in #671, except that the notification should say who removed you from the room, and an optional reason.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
`user-test` was approved successful, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix still.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Still things to fix.

**Comment by azlancpool** [comment]
Comments was fixed, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Still things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK
