### ISSUE TITLE
Grant moderator ship to a person that doesn't have it (9.6) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#630]
A moderator should be able to add the moderator status for someone else. Since this is something that only happens in a room, this functionality should probably be possible to access from the user panel in the roster. Once you have chosen to change the role, you will be asked what the new role should be, and what the reason should be.

We might be able to unify these behaviors, since there are many different role-transition that a user can do to another user, we might do these as one piece of functionality, but it might also be clearer for a user to have specific actions. We should test and see what's better.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
I don't consider this done, since there are several TODOs that were introduced in this code that were not resolved - which have to do with this specific functionality.

**Comment by MauroVelasco** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, small text to fix, but otherwise it's fine.

**Comment by azlancpool** [comment]
The text was improved, so it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
All good.
