### ISSUE TITLE
Be notified of success or failure of the moderator grant (9.6)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#631]
When you try to change a non-moderator into a moderator, you should get a notification of success or failure, and if failure why it failed.
      
 **Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
There are things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
This issue is ready to  be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK
