### ISSUE TITLE
Display notification when someone gets to be a moderator (9.6)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#632]
When a person has their role changed to being a moderator, a notification should be displayed to any other user in the conversation view. This should include who changed the status, what the new status is, and the optional reason.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by peterpalau** [comment]
We think the issue is ready to be tested by the users.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Nope. Still not  fixed.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
I feel like you're not even looking at the end result here, just changing things mechanically or at random...

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by MauroVelasco** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK.
