### ISSUE TITLE
Be notified of success or failure of the moderator revocation (9.7)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#635]
When you try to change a moderator into a non-moderator, you should get a notification of success or failure, and if failure why it failed.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
There are some things, and comments which haven't been fixed on some of the commits.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK.
