### ISSUE TITLE
Display notification when someone is removed as moderator (9.7)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#636]
When a person has their role changed away from being a moderator, a notification should be displayed to any other user in the conversation view. This should include who changed the status, what the new status is, and the optional reason.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
It seems like some commits are missing. The two referenced commits here are clearly not enough for this functionality, right?

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
OK.
