### ISSUE TITLE
Be notified when you are removed as moderator (9.7)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#637]
When an administrator changes the role of an moderator to not be a moderator anymore, the user should be notified of this. Since this is something that only can happen when you're inside a room, the notification should happen somewhere in the room view, but I'm not sure if it makes sense to put it in the conversation view, or outside.

The notification should show who removed the status, what the reason was, and also what your new role in the room is.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
There are several commits with things to fix here.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK
