### ISSUE TITLE
Configure room after creation (10.2)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#640]
Just as when creating a configured room #639, you should be able to configure the room after it has been created. This should be possible to access from inside the room view if you are of the right association to be able to do that (owner, I think).

The same kind of ideas around how to format and display the configuration options from #639 should be applied here.

This story should be done after #639 so we can reuse those configuration views.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by Cris2760** [comment]
Blocked by #639

**Comment by peterpalau** [comment]
After the user tests, we agreed that the navigation buttons of the configuration assistant window should be disabled if any error is present on the current configuration page.

**Comment by olabiniV2** [comment]
Looks good.

**Comment by peterpalau** [comment]
We realized some inconsistent behavior in the configuration assistant that is registered via #762. We should back this issue to doing.

**Comment by olabiniV2** [comment]
Reviewed, OK

**Comment by azlancpool** [comment]
We should change the title of the window

**Comment by Cris2760** [comment]
Blocked by #767

**Comment by olabiniV2** [comment]
OK
