### ISSUE TITLE
Notify people in a room of configuration changes (10.2, 10.2.1)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#641]
**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by Cris2760** [comment]
Ready for @olabiniV2  review

**Comment by olabiniV2** [comment]
I've reviewed the code and there are some things to fix here and there before this is done.

**Comment by Cris2760** [comment]
Comments are fixed, it's ready for @olabiniV2  review.

**Comment by olabiniV2** [comment]
I'm confused - it says the comments are fixed, but nothing is marked for this issue. Where is the code related to those fixes???

**Comment by MauroVelasco** [comment]
> I'm confused - it says the comments are fixed, but nothing is marked for this issue. Where is the code related to those fixes???

I'm sorry the commits were not tagged to issue id, now has been tagged. Will not happened again.

**Comment by olabiniV2** [comment]
OK, review done. I think there's only two comments left to fix - the one about "NonAnonymous", and the one about custom types for the anonymity type. Once those two are fixed, this can be considered done, and since these two can be done together.

**Comment by MauroVelasco** [comment]
> OK, review done. I think there's only two comments left to fix - the one about "NonAnonymous", and the one about custom types for the anonymity type. Once those two are fixed, this can be considered done, and since these two can be done together.

Fixes applied in commits 1a4be2760859592c0a330574009b37eb3264e955 and d123feb8ce2f873a1fd7f80f8b939a7cda8731ac

**Comment by olabiniV2** [comment]
OK, looks good.
