### ISSUE TITLE
Display notification when someone gets to be a owner (10.3)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#643]
All other people that are currently in a room should see a notification when someone is added as owner. This should be  visible in the conversation view, but also be updated in the roster. The message might look something like this: "user1 gave owner status to user2", or something like that. If a reason is given, that should also be displayed.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
I think some commits must be missing here.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
OK
