### ISSUE TITLE
Revoke ownership to a owner (10.4) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#645]
An owner can revoke owner status for another owner. For now, for ease of development, we should give access to this functionality from the user panel in the roster.

When revoking the ownership you should be able to provide an optional reason for it.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
I think some commits are missing here too.

**Comment by olabiniV2** [comment]
OK
