### ISSUE TITLE
Display notification when someone is removed as owner (10.4)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#647]
All other people that are currently in a room should see a notification when someone is removed as owner. This should be visible in the conversation view, but also be updated in the roster. The message might look something like this: "user1 removed owner status for user2 - user2 is now a participant", or something like that. If a reason is given, that should also be displayed.

 **Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
It seems things are missing here, right?

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Still things to fix.

**Comment by olabiniV2** [comment]
OK
