### ISSUE TITLE
Be notified when you are removed as owner (10.4)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#648]
When an owner decides to remove owner affiliation for a user, that user should be notified.

Since this, at least in theory, can happen even when the owner or the other owner are not actually inside the room, we might need two notifications - one when there is no room view open, and one when it's open. The notification should say different things depending on what the new affiliation of the user is.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
`user-test` was approved successful, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some comments on these commits.

**Comment by azlancpool** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Thing to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK
