### ISSUE TITLE
Grant admin status to a person that doesn't have it (10.6) (Optionally provide reason notified of success or failure of the admin grant)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#649]
An administrator or owner can add administrator privileges to a person, changing their affiliation to "administrator". For now, for ease of development, we should give access to this functionality from the user panel in the roster. We should also consider how to do it for a user who is not actively in a room. For now, this could be a standalone dialog.

When adding administrator privileges. you should be able to provide an optional reason for it.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by MauroVelasco** [comment]
Ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, I've gone through the code, and there's a lot of smaller things to fix.

**Comment by peterpalau** [comment]
The issue is done to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, there's one race condition to fix, but except for that, things are good.

**Comment by azlancpool** [comment]
We improved the messages shown in the dialog and remove the race condition, so it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some things to fix here.

**Comment by azlancpool** [comment]
All small things was fixed, it's ready to be review by @olabiniV2

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, one more thing to fix.

**Comment by peterpalau** [comment]
We did another update to the documentation.

**Comment by azlancpool** [comment]
We improved the documentation, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Another round of review of the documentat is necessary.

**Comment by azlancpool** [comment]
it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK.

**Comment by azlancpool** [comment]
@olabiniV2, we added some commits related with styles in help text for affiliation-dialog, so we will add code-review again

**Comment by olabiniV2** [comment]
Looks fine.
