### ISSUE TITLE
Display notification when someone gets to be an admin (10.6)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#650]
All other people that are currently in a room should see a notification when someone is added as admin. This should be  visible in the conversation view, but also be updated in the roster. The message might look something like this: "user1 gave admin status to user2", or something like that. If a reason is given, that should also be displayed.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by peterpalau** [comment]
This issue is ready to be reviewed.

**Comment by olabiniV2** [comment]
OK, some small things to fix here.

**Comment by peterpalau** [comment]
Okay the comments has been fixed but we think the messages that are displayed to the user should be reviewed by the team in order to mark this issue as `done`.

**Comment by olabiniV2** [comment]
Some things to fix again here.

**Comment by peterpalau** [comment]
The comments has been fixed and should be reviewed now by @olabiniV2.

**Comment by olabiniV2** [comment]
There's still some texts that aren't correct here. If it was reviewed, mistakes were made - some texts are still not even grammatical...

**Comment by peterpalau** [comment]
Yeap, that is what I said because I think the texts were not reviewed.

**Comment by olabiniV2** [comment]
Except for that, the review is done. So, I'll mark this as needing user testing.

**Comment by peterpalau** [comment]
The messages were updated and the issue is ready again to be reviewed by @olabiniV2.

**Comment by peterpalau** [comment]
The issue is ready to be reviewed by @olabiniV2.

**Comment by olabiniV2** [comment]
OK, some things to fix here.

**Comment by MauroVelasco** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some serious multithreading issues to solve here.

**Comment by olabiniV2** [comment]
When solving synchronization issues, you can't just slap a mutex on it and think that you're done. You have to think about exactly HOW that code is used from everywhere else, so that you don't introduce any bad side effects...

**Comment by peterpalau** [comment]
Okay the issue is ready to be reviewed.

**Comment by peterpalau** [comment]
Okay we discovered some problems this need more work.

**Comment by olabiniV2** [comment]
Some things left to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some small things left to fix.

**Comment by azlancpool** [comment]
`user-test` was approved successful, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Sounds good.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Still things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by MauroVelasco** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK.
