### ISSUE TITLE
Revoke admin status to an admin (10.7) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#652]
An owner can revoke admin status for a person. For now, for ease of development, we should give access to this functionality from the user panel in the roster.

When revoking the adminship you should be able to provide an optional reason for it.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by MauroVelasco** [comment]
This issue is related to #649

**Comment by olabiniV2** [comment]
Sorry, I can't review the code for this, since there are no commits that actually reference it...

**Comment by olabiniV2** [comment]
There's still nothing that references this, so nothing to review....

**Comment by olabiniV2** [comment]
OK, looks good.
