### ISSUE TITLE
Be notified of success or failure of the admin revocation (10.7)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#653]
When removing the admin status for a user, you should be told if the operation succeeded or failed, and if it failed, why it failed.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by peterpalau** [comment]
Okay some work has been done that in some way is related to this issue. We will be pushing the new changes shortly.

**Comment by azlancpool** [comment]
The user-tests has been done, this issue is ready to be reviewed by @olabiniV2

**Comment by azlancpool** [comment]
A little change related with a message improve will be updated, for this reason the status will change to `Doing` again

**Comment by azlancpool** [comment]
> A little change related with a message improve will be updated, for this reason the status will change to `Doing` again

I'm sorry, this change is not in this issue, so, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Looks fine to me.
