### ISSUE TITLE
Be notified when you are removed as admin (10.7)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#655]
When an owner decides to remove admin affiliation for a user, that user should be notified.

Since this, at least in theory, can happen even when the owner or the admin are not actually inside the room, we might need two notifications - one when there is no room view open, and one when it's open. The notification should say different things depending on what the new affiliation of the user is.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, so, I have noticed that "affiliation" and "previousAffiliation" are sent in in different orders in many different places around the code base. That's not great, and it can cause a lot of confusion. I think maybe we should actually create a small helper struct to avoid this problem completely:
```
type affiliationUpdate struct {
   new Affiliation
   previous Affiliation
}
```

We need to avoid situations where small changes compile, but cause unexpected behavior. So I think we should do this refactor before this story can be considered finished.

**Comment by MauroVelasco** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Looks fine to me.

**Comment by peterpalau** [comment]
This issue has been opened because the messages should be reviewed by the users during the user-tests.

**Comment by azlancpool** [comment]
Already the user-tests has been done.
We implemented some functionality in order to get a friendly message to be shown in the notification bar, this changes should be reviewed by @olabiniV2

**Comment by azlancpool** [comment]
A little change related with a message improve will be updated, for this reason the status will change to `Doing` again

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
There's one fairly large thing to fix, so I'll put this back in doing.

**Comment by peterpalau** [comment]
The issue is ready to be reviewed by @olabiniV2.

**Comment by olabiniV2** [comment]
Some more things to look at. Also, I asked that all places that did this kind of switch would be changed. Did that happen?-

**Comment by peterpalau** [comment]
> Some more things to look at. Also, I asked that all places that did this kind of switch would be changed. Did that happen?-

Yes the `switch` was changed in every place.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, looks fine.
