### ISSUE TITLE
Fix the layout problem in the room window when the user join in a room which it's already open.

### ISSUE THREAD

**Issue by MauroVelasco** [coyim/coyim#676]
When a user try to join in a room which is already opened the window layout is altered.

![layout-altered](https://user-images.githubusercontent.com/2516223/100480671-ef809400-30bf-11eb-88db-414e3b447872.png)

**Comment by MauroVelasco** [comment]
Ready to code review by @olabiniV2

**Comment by olabiniV2** [comment]
Looks good to me.
