### ISSUE TITLE
Show loading overlay in lobby window

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#677]

**Comment by olabiniV2** [comment]
OK, there are some outstanding comments to fix here.

**Comment by peterpalau** [comment]
Ok, the user testing has finished, so this is ready to be closed.

**Comment by peterpalau** [comment]
Actually, I was to fast in closing this issue, there are some pending comments to do.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Looks good.

**Comment by azlancpool** [comment]
> Looks good.

Great! I'm going to close this issue.
