### ISSUE TITLE
Update the logic for creating and using components such as the notifications and the spinner throughout the GUI package

### ISSUE THREAD

**Issue by peterpalau** [coyim/coyim#683]
The idea is to refactor the code that uses the components that we have been creating, in order to be consistent and clear in how these components should be used.

**Comment by peterpalau** [comment]
Ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some things to fix.

**Comment by peterpalau** [comment]
The issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Looks good.
