### ISSUE TITLE
Create a notification feature to use in the room

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#684]

**Comment by peterpalau** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some things to fix here.

**Comment by peterpalau** [comment]
The issue is ready to be reviewed again by @olabiniV2.

**Comment by olabiniV2** [comment]
OK, looks fine.

**Comment by peterpalau** [comment]
Good, the issue is ready to be closed.
