### ISSUE TITLE
Renames the `widget` method name on all structs that aren't supposed to implement the `withWidget` interface

### ISSUE THREAD

**Issue by peterpalau** [coyim/coyim#686]
In lot of places in the code we have the `widget` method implemented in some structs that return a different type than the specified in the interface, that is because those structs are not supposed to implement the `withWidget` interface and we decided to rename those methods.

**Comment by MauroVelasco** [comment]
Ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Lots of things to fix.

**Comment by azlancpool** [comment]
All comments are done, so it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, looks good.
