### ISSUE TITLE
Windows build isn't producing useful builds

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#688]
The current Windows build generates a package which doesn't contain all necessary components. This is likely because of a combination of us using new libraries, and also some package names being updated in the msys version we are using. Specifically, in the Windows 10 Pro version I tested, two DLLs were missing: `libffi-7.dll` and `libbrotlidec.dll`. In our last release, `libffi-6.dll` was part of the package, but it's not part of the package now. My assumption is that the FFI library was updated by msys. The other DLL is completely new.

This story is both about fixing these problems, and trying out that CoyIM now works on Windows 10 again.

**Comment by rafaelbonifaz** [comment]
Just tested in Windows 10 and we are missing libbrotlicommon.dll

**Comment by rafaelbonifaz** [comment]
Just tested and now it is working.
