### ISSUE TITLE
Display to whom the position is changed.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#698]

**Comment by azlancpool** [comment]
The occupant information was added in the occupant update dialog, It's ready to do user-test

**Comment by peterpalau** [comment]
We need to make a small change to the message shown to the user as part of this story.

**Comment by peterpalau** [comment]
We decided that this story should be in code review and not user testing because we already made improvements to user reviews that were done previously.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
OK, looks good.
