### ISSUE TITLE
Improve success notification adding info related with role updated.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#699]

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Sorry, I can't review the fixes, since there's no commits tagged with this issue.

**Comment by azlancpool** [comment]
I'm sorry, a changed to `user-test` instead of `code-review`

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Looks OK.
