### ISSUE TITLE
Improve success notification adding info related with position updated.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#701]

**Comment by olabiniV2** [comment]
One small issue to fix before this is done.

**Comment by olabiniV2** [comment]
Some things to fix.

**Comment by azlancpool** [comment]
All comments are related with functions that currently doesn't exist, Those functions were removed when the texts structure was improved.
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, looks good.
