### ISSUE TITLE
Failing Test_builderForDefinition_useGoFileIfXMLDoesntExists

### ISSUE THREAD

**Issue by sacurio** [coyim/coyim#726]
The test is failing in Windows with the following output:

```
... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x7FF6551E9853)

C:/Program Files/Go/src/runtime/panic.go:969
  in gopanic
C:/Program Files/Go/src/runtime/panic.go:212
  in panicmem
C:/Program Files/Go/src/runtime/signal_windows.go:246
  in sigpanic
ui_reader_test.go:134
  in getModTime
ui_reader_test.go:142
  in UIReaderSuite.Test_builderForDefinition_useGoFileIfXMLDoesntExists
C:/Program Files/Go/src/reflect/value.go:460
  in Value.call
C:/Program Files/Go/src/reflect/value.go:321
  in Value.Call
C:/Program Files/Go/src/runtime/asm_amd64.s:1373
  in goexit

```

**Comment by olabiniV2** [comment]
I'm not OK with this fix to be honest. The whole point of this implementation was to have a local directory look up, and this fix just removes that functionality.

**Comment by peterpalau** [comment]
> I'm not OK with this fix to be honest. The whole point of this implementation was to have a local directory look up, and this fix just removes that functionality.

Okay I don't see the point of "why a local directory look up" but we implemented something simple.

**Comment by peterpalau** [comment]
Okay after some tests we did we found this is still not working in some cases. We need to find why it works in some cases and why not in others.

**Comment by olabiniV2** [comment]
Not fixed yet.

**Comment by olabiniV2** [comment]
Small fix needed.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
OK.

**Comment by peterpalau** [comment]
Okay this issue is fixed.
