### ISSUE TITLE
Failing Test_resolve_resolvesCorrectly

### ISSUE THREAD

**Issue by sacurio** [coyim/coyim#730]
The test is failing in Windows with the following output:

```
dns_test.go:53:
    c.Assert(err, IsNil)
... value *net.OpError = &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc00025b9e0), Addr:(*net.TCPAddr)(0xc00025ba10), Err:(*os.SyscallError)(0xc000288000)} ("read tcp 127.0.0.1he remote host.")
```

**Comment by olabiniV2** [comment]
Is this still failing?

**Comment by peterpalau** [comment]
This is not failing anymore and we don't have a clear idea of why. Our assumption is that it failed due to a bad configuration of the Windows virtual machine. Anyway, it's not failing anymore.

**Comment by olabiniV2** [comment]
Hmm OK. I'll close it for now, and set up Windows CI.

**Comment by olabiniV2** [comment]
Nope, this now fails in the CI

**Comment by olabiniV2** [comment]
Is this fixed now, since the Windows CI works? Or is it disabled or something?

**Comment by peterpalau** [comment]
> Is this fixed now, since the Windows CI works? Or is it disabled or something?

It's fixed. All the work related to this issue was referenced.

**Comment by olabiniV2** [comment]
Reviewed, OK
