### ISSUE TITLE
Failing Test_conn_ReceivePong

### ISSUE THREAD

**Issue by sacurio** [coyim/coyim#737]
The test is failing in Windows with the following output:

```
ping_test.go:51:
    c.Assert(t1, Not(Equals), conn.lastPongResponse)
... obtained time.Time = time.Time{wall:0xc00cfdf76de8001c, ext:48525401, loc:(*time.Location)(0xe43c00)} ("2021-03-18 11:31:25.7701791 -0500 -05 m=+0.048525401")
... expected time.Time = time.Time{wall:0xc00cfdf76de8001c, ext:48525401, loc:(*time.Location)(0xe43c00)} ("2021-03-18 11:31:25.7701791 -0500 -05 m=+0.048525401")
```

**Comment by peterpalau** [comment]
So, we found that the time precision in Windows is really slow. It takes between 10 to 15 ms in Windows to update the time.

More information can be found at:

- https://stackoverflow.com/questions/57285292/why-does-time-now-unixnano-returns-the-same-result-after-an-io-operation
- https://github.com/golang/go/issues/11313

We will continue investigating on this and see what could be our alternatives.

Also, we don't know if this issue could be a problem for Coy.

**Comment by peterpalau** [comment]
> It takes between 10 to 15 ms in Windows

More or less like `15.6 milliseconds`.

**Comment by olabiniV2** [comment]
I'm sorry, but this is not an acceptable solution to this problem. Tests that sleep a specific amount to work, will sometimes fail for no obvious reason, or they will spend way too much time sleeping. There should exist a better solution here.

**Comment by olabiniV2** [comment]
This needs to be rethought.

**Comment by olabiniV2** [comment]
This solution is OK. There were several other similar solutions which you should have considered here, though - instead of getting stuck in investigation of Windows time management.

**Comment by peterpalau** [comment]
I am going to take it a look as I have time for it. Thank you very much.
