### ISSUE TITLE
Add styles to messages based on their type and function.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#745]

**Comment by peterpalau** [comment]
After some internal discussion in our user testing meeting with the team, we decided to make some mockups proposals to have a better idea of how the messages could appear.

**Comment by peterpalau** [comment]
Here are the mockups

![Issue-745](https://user-images.githubusercontent.com/12257885/122428707-c63e2d00-cf57-11eb-964d-7794bb5669ab.jpg)

**Comment by peterpalau** [comment]
After the user testing, we have to work a little bit more with the warnings dialog.

**Comment by olabiniV2** [comment]
I don't see any indication that https://github.com/coyim/coyim/commit/c801a63462adbe79600e84917385596330af8a84 has been fixed.

**Comment by peterpalau** [comment]
> I don't see any indication that [c801a63](https://github.com/coyim/coyim/commit/c801a63462adbe79600e84917385596330af8a84) has been fixed.

Our mistake. The fix is available via https://github.com/coyim/coyim/commit/19e16ac7740e002c346c618c0ee465d065485133#diff-0eea0e1edb2c2d5f27533c70e60897adb22ed84e107859ddb1f8cf9749fe71adR214.

**Comment by olabiniV2** [comment]
OK.

**Comment by peterpalau** [comment]
The issue is ready to be closed.
