### ISSUE TITLE
Tests `UtilsSuite.Test_ifExistsDir_returnsTheValueButNothingElseIfReadingDirFails` and `FileSuite.Test_safeWrite_failsIfImpossibleToWriteFile` are failing on Windows

### ISSUE THREAD

**Issue by peterpalau** [coyim/coyim#747]
This are the tests output when they fails on windows:

```shell
FAIL: file_test.go:187: FileSuite.Test_safeWrite_failsIfImpossibleToWriteFile

file_test.go:193:
    c.Assert(e, ErrorMatches, ".*denied.*")
... value = nil
... regex string = ".*denied.*"
... Error value is nil
```

```shell
FAIL: utils_test.go:55: UtilsSuite.Test_ifExistsDir_returnsTheValueButNothingElseIfReadingDirFails

utils_test.go:70:
    c.Assert(res, DeepEquals, []string{"foo", "bar"})
... obtained []string = []string{"foo", "bar", "C:\\cygwin64\\tmp\\193946383\\goodbye.conf", "C:\\cygwin64\\tmp\\193946383\\hello.conf"
}
... expected []string = []string{"foo", "bar"}
... Difference:
...     []string[4] != []string[2]

```

**Comment by peterpalau** [comment]
All of this happens because since we are using `msys2` to run Coy on Windows, the tool doesn't know anything about Windows ACL permissions using `icacls`.

So, if you make a directory pure inaccessible using `icacls`, you are going to be able to open that directory and see all the content inside it. We need to think of another approach to run these test cases.

**Comment by peterpalau** [comment]
We found something really interesting.

The following code:

https://github.com/coyim/coyim/blob/deefedfe5c09fed96005db130ef5bfa36d2933dd/vendor/github.com/hydrogen18/stalecucumber/pickle_machine.go#L352-L365

We suspect it is leading to an error we have in Windows systems. The cause is that in the reading process, it returns an `EOF` error without any results. I think that it could be something related to how the length of the bytes is calculated.

It would have been better to use `ioutil.ReadFile()` I think.

**Comment by peterpalau** [comment]
Okay, I want to write a small update about this.

Originally, we opened an [issue](https://github.com/msys2/msys2-runtime/issues/45#issuecomment-849843066) in the [MSYS2-packages](https://github.com/msys2/MSYS2-packages) repository. That issue was moved to the [msys2-runtime](https://github.com/msys2/msys2-runtime) repository.

After that, we got in touch with the team behind `cygwin` and they gave us an idea of how to fix this. Basically, the `cygdrop` command, which is available as part of the `cygutils` package, can be used to fix this issue.

Our friend at `msys2` is working on a [PR](https://github.com/msys2/MSYS2-packages/pull/2518) that will add the `cygutils` package and when merged, it will be available in the `msys2` [packages list](https://packages.msys2.org/updates).

**Comment by peterpalau** [comment]
The full email thread can be read via https://cygwin.com/pipermail/cygwin/2021-May/248594.html.

**Comment by olabiniV2** [comment]
Reviewed, OK

**Comment by peterpalau** [comment]
The last commits are ready to be reviewed by @olabini @olabiniV2

**Comment by olabiniV2** [comment]
Reviewed, OK

**Comment by peterpalau** [comment]
The issue is ready to be closed.
