### ISSUE TITLE
Test `Test_ifExistsDir_returnsTheValueButNothingElseIfReadingDirFails` is failing in Windows Server 2016 and Windows Server 2019

### ISSUE THREAD

**Issue by peterpalau** [coyim/coyim#749]
The output is the following:

```
FAIL: utils_test.go:55: UtilsSuite.Test_ifExistsDir_returnsTheValueButNothingElseIfReadingDirFails

utils_test.go:70:
    c.Assert(res, DeepEquals, []string{"foo", "bar"})
... obtained []string = []string{"foo", "bar", "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\621723115\\goodbye.conf", "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\621723115\\hello.conf"}
... expected []string = []string{"foo", "bar"}
... Difference:
...     []string[4] != []string[2]
```

**Comment by peterpalau** [comment]
This has been something really hard to know why it happens. We suspect that it could be a potential security bug in **msys2**.

We decided to open an [issue](https://github.com/msys2/MSYS2-packages/issues/2513) in the **msys2** repository and have their help in understanding this and maybe, find a solution.

**Comment by olabiniV2** [comment]
Reviewed, OK

**Comment by peterpalau** [comment]
The last commits are ready to be reviewed by @olabini @olabiniV2

**Comment by olabiniV2** [comment]
Reviewed, OK

**Comment by peterpalau** [comment]
The issue is ready to be closed.
