### ISSUE TITLE
Files and folders created during testing stage in Windows are not being deleted due to the "the resource is in use by another process" error 

### ISSUE THREAD

**Issue by peterpalau** [coyim/coyim#753]
Solving this should be done in a way that does not change the signature of the tests.

**Comment by olabiniV2** [comment]
Is this fixed now, since the Windows CI works? Or is it disabled or something?

**Comment by peterpalau** [comment]
I updated the tests but I rollback the changes because some of the changes changed too the sematic of the tests.

**Comment by olabiniV2** [comment]
I'm confused. The tests are passing on Windows even though you rolled back the tests? So, is this an issue or not???

**Comment by peterpalau** [comment]
The tests are working. The problem is that when you run these tests on Windows, they left behind a lot of temporary folders that couldn't be deleted because of the "...the directory is in use by another resource..." error.

**Comment by olabiniV2** [comment]
I'll take point on that. @peterpalau can you just give me a pointer to one test that exemplifies this problem?

**Comment by olabiniV2** [comment]
Hmm. I've investigated a bit, and I don't see the "the directory is in use by another resource" messages in the CI. For example, looking at this https://github.com/coyim/coyim/runs/3206896022?check_suite_focus=true seems fine, and no output from Windows. Why is that?

**Comment by peterpalau** [comment]
> Hmm. I've investigated a bit, and I don't see the "the directory is in use by another resource" messages in the CI. For example, looking at this https://github.com/coyim/coyim/runs/3206896022?check_suite_focus=true seems fine, and no output from Windows. Why is that?

It is because the errors that are thrown when trying to delete the folders are not registered in the CI.

For example, the following line

https://github.com/coyim/coyim/blob/630ea78d07f11ad5b789c4d5fb196bb500342e5f/config/importer/pidgin_test.go#L267

Will never succeed in Windows because in the next lines

https://github.com/coyim/coyim/blob/630ea78d07f11ad5b789c4d5fb196bb500342e5f/config/importer/pidgin_test.go#L275-L276

`os.Create` returns a file that can be used for I/O and we never close it.

**Comment by olabiniV2** [comment]
Just to make this issue very clear for anyone reading it later. The line `os.RemoveAll(dir)` will return an error, but since this is being ignored for these tests, we never see them. That is the "the resource is in use by another process" error. 

The real issue here is that none of these deletions actually will succeed on Windows, leaving a large amount of temporary directories. The end goal of this story is to actually make sure these are removed as part of the test process.

**Comment by olabiniV2** [comment]
I will approach this in two steps. First, I will change all the tests to report errors on this kind of cleanup. Then, I will fix them in a semantics-preserving way.
But the first step is to print out on windows the temp directory, so we can see if there are any remaining directories there.

**Comment by olabiniV2** [comment]
OK, so, the last commit seems to have fixed all problems in the config directory. 
But after running, with logging, it's clear that we have other code that doesn't clean up directories properly. Specifically, these directories were not there before:
```
-rw-r--r-- 1 runneradmin None 1347 Aug  2 18:20 082880451
-rw-r--r-- 1 runneradmin None    0 Aug  2 18:30 153775462
-rw-r--r-- 1 runneradmin None 1347 Aug  2 18:30 156236531
-rw-r--r-- 1 runneradmin None    0 Aug  2 18:20 263816433
-rw-r--r-- 1 runneradmin None    0 Aug  2 18:30 286692744
-rw-r--r-- 1 runneradmin None  106 Aug  2 18:30 302840410
-rw-r--r-- 1 runneradmin None    0 Aug  2 18:20 389799836
-rw-r--r-- 1 runneradmin None    0 Aug  2 18:20 491198810
-rw-r--r-- 1 runneradmin None    0 Aug  2 18:30 617851277
-rw-r--r-- 1 runneradmin None  106 Aug  2 18:30 689731057
-rw-r--r-- 1 runneradmin None  107 Aug  2 18:30 777754990
-rw-r--r-- 1 runneradmin None  106 Aug  2 18:30 970307573
drwxr-xr-x 1 runneradmin None    0 Aug  2 18:29 coyim/
drwxr-xr-x 1 runneradmin None    0 Aug  2 18:19 coyim-schema094561247/
drwxr-xr-x 1 runneradmin None    0 Aug  2 18:19 coyim-schema117530947/
drwxr-xr-x 1 runneradmin None    0 Aug  2 18:30 coyim-schema176617255/
drwxr-xr-x 1 runneradmin None    0 Aug  2 18:30 coyim-schema503298887/
drwxr-xr-x 1 runneradmin None    0 Aug  2 18:30 coyim-schema517016459/
drwxr-xr-x 1 runneradmin None    0 Aug  2 18:30 coyim-schema902909199/
-rw-r--r-- 1 runneradmin None   22 Aug  2 18:20 non-existing-file.bin-directory-567143975
-rw-r--r-- 1 runneradmin None   22 Aug  2 18:30 non-existing-file.bin-directory-567765347
```

That's 21 directories that shouldn't be there. The rest of this story will be to find these places and fix them.

**Comment by olabiniV2** [comment]
The `coyim` directory is used to store icons, and since it won't generate more directories, that should be safe.

**Comment by olabiniV2** [comment]
After the latest commits, the only missing files generated are:
```
-rw-r--r-- 1 runneradmin None 22 Aug  2 19:41 non-existing-file.bin-directory-628142075
-rw-r--r-- 1 runneradmin None 22 Aug  2 19:51 non-existing-file.bin-directory-690204699
```

**Comment by olabiniV2** [comment]
By removing the temporary file before sending on the channel, we make sure that these files are removed as well.

**Comment by olabiniV2** [comment]
This story is now done - no temporary directories are left, and all potential Windows problems with re-using resources have been fixed.
