### ISSUE TITLE
Investigate an alternative to HTML to give text formatting.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#756]

**Comment by peterpalau** [comment]
We have found three possible solutions so far to give format to a label text:

- Using [Pango attributes](https://developer.gnome.org/pygtk/stable/class-pangoattrlist.html)
- Using [Pango text markup](https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-markup) either with CSS or without CSS
- Using a [pattern of underlines](https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-pattern) we want under the existing text

Each of them has __pros__ and __cons__ that we detail below.

**Comment by peterpalau** [comment]
#### Using Pango attributes

 ![Screenshot from 2021-07-01 12-05-02](https://user-images.githubusercontent.com/12257885/124162904-9f5a1d80-da64-11eb-8945-fbdce11f1ff1.png)

Basically, a Pango attribute list is an object holding attributes that are applied to a section of text. It sounds like we need.

Pango has many different attributes that can be used for styling a text. Just to mention a few, the *font-weight*, *style*, *size*, ?*background*, *color*, and *family*, etc. Those attributes accept two indexes. The `start_index` and the `end_index` can be used to define what section of the text should take the format given by the attributes.

Using Pango attributes could be very good from a security point of view.

I think this is one of the best possible solutions to use.

**Comment by sacurio** [comment]
The second possible solution is the use of _Pango text markup_. The problem with this option is related to the use of HTML Markup inside of the label, this is an insecure way to add styles inside the text, for this reason, we can consider this option not useful in terms of security, for minimizing the surface of attack.

The next are screenshots that shows how we can add styles using _Pango text markup_:

![imagen](https://user-images.githubusercontent.com/1084317/124161274-d3ccda00-da62-11eb-974b-855de23395f4.png)

![imagen](https://user-images.githubusercontent.com/1084317/124161288-d92a2480-da62-11eb-95cf-2be96181795d.png)

**Comment by sacurio** [comment]
The third solution uses the Pattern of underlines for a section of text that is inside of a label. Basically, we can define the start position and the length of the section text that will be underlined. This option is secure and simple, uses a behavior provided by Pango directly. A possible disadvantage could be the way to highlight the target text section just with an underline format, which avoids the possibility of adding styles.

The next are screenshots that show how we can add styles using _pattern of underlines:_

![imagen](https://user-images.githubusercontent.com/1084317/124179213-1ea51c80-da78-11eb-8b53-55eae2e593c9.png)

![imagen](https://user-images.githubusercontent.com/1084317/124179224-2369d080-da78-11eb-8429-429aeff835b6.png)

**Comment by peterpalau** [comment]
In our team meeting to discuss the solutions, we decided to use [Pango attributes](https://developer.gnome.org/pygtk/stable/class-pangoattrlist.html).

**Comment by peterpalau** [comment]
The spike is done.
