### ISSUE TITLE
Update the Download Links in Website

### ISSUE THREAD

**Issue by linuxvai** [coyim/coyim#766]
The download links provided in the website are broken because of the demise of Bintray. Please update the links to appropriate binary releases. Its urgent!

**Comment by olabiniV2** [comment]
Hi,

I'm very sorry about this - we are currently planning a new pre-release which will be available sometime next week. In the meantime, you can download the binaries from the Github Release page, here: 
https://github.com/coyim/coyim/releases/tag/v0.3.11

Thanks
