### ISSUE TITLE
Add the items to the banned occupant list in the same order as the add dialog.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#769]

**Comment by peterpalau** [comment]
The issue is ready for user testing.

**Comment by olabiniV2** [comment]
The resolution for one of the code review comments haven't been tagged for this issue, so it can be tracked...
Not accepted.

**Comment by IvanJijon** [comment]
> The resolution for one of the code review comments haven't been tagged for this issue, so it can be tracked...
> Not accepted.

The comment has been fixed in commit 30c8dd1.

**Comment by azlancpool** [comment]
So all comments were replied, it's ready to be reviewed

**Comment by azlancpool** [comment]
First we need to do user-test instead of code-review

**Comment by olabiniV2** [comment]
OK
