### ISSUE TITLE
Ask the user if they want to leave the room or just close the window ?

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#770]

**Comment by azlancpool** [comment]
We decided in `user-test` that this issue should be blocked by #675, and it will be worked in a time-box of 2 hours. If the issue #675 can't be solved after the time-box, this issue won't be part of the release

**Comment by azlancpool** [comment]
As agreed during the mockup presentation, we need to work on:

- Set default focus on `Cancel` button
- Add an icon and improve the mockup design

**Comment by olabiniV2** [comment]
OK
