### ISSUE TITLE
Error when canceling room configuration and trying to create same room again

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#774]
If you follow these steps:
- `Chat Rooms` -> `Create Room`
- Enter a name for the room
- Choose a server
- Choose `Add custom room configuration`
- Press `Configure Room`
- Press `Cancel`
- Press `Configure Room` again

At this point, an error happens. An example from the debug log output when I tried this looks like this:
```
ERRO[0285] Trying to leave a room that is not present in the manager  account=olatest@testjabber.autonomia.digital component=session room=foo1foo2@conf.testjabber.autonomia.digital
ERRO[0287] Got a presence error                          account=olatest@testjabber.autonomia.digital component=session error="&{{jabber:client error}   cancel  {{urn:ietf:params:xml:ns:xmpp-stanzas gone} xmpp:%!s(&lt;nil&gt;)?join} <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}" from=foo1foo2@conf.testjabber.autonomia.digital
ERRO[0287] Something wrong happened during the request   account=olatest@testjabber.autonomia.digital component=session error="received an error from the server" requestType=create-reserved-room where=mucRequest
ERRO[0352] Got a presence error                          account=olatest@testjabber.autonomia.digital component=session error="&{{jabber:client error}   cancel  {{ } } <nil> <nil> <nil> <nil> <nil> <nil> <nil> 0xc0004925e0 <nil> <nil>}" from=foo1foo3@conf.testjabber.autonomia.digital
DEBU[0352] getRoomView(): trying to get a not connected room  account=olatest@testjabber.autonomia.digital component=gui room=foo1foo3@conf.testjabber.autonomia.digital
```

Another story is created to track the problem that the UI doesn't handle this error properly. This is #773

**Comment by sacurio** [comment]
Working on this issue, we realized that the `Configure Room` label is not updated once the user cancels the creation of the configured room. The label that appears is `Create Room` when it should be `Configure Room`.

**Comment by azlancpool** [comment]
There are still a few things to fix.

**Comment by IvanJijon** [comment]
From the above mentioned logs (see https://github.com/coyim/coyim/issues/774#issue-984534613), this first line was handled in the issue #781.
This was logged because the room wasn't present in the Room Manager since we were still configuring it. It is not logged anymore.
```
ERRO[0285] Trying to leave a room that is not present in the manager  account=olatest@testjabber.autonomia.digital component=session room=foo1foo2@conf.testjabber.autonomia.digital
```

This second line was handled in #773 (see https://github.com/coyim/coyim/issues/773#issuecomment-911079513). It is not logged anymore.

```
ERRO[0287] Got a presence error                          account=olatest@testjabber.autonomia.digital component=session error="&{{jabber:client error}   cancel  {{urn:ietf:params:xml:ns:xmpp-stanzas gone} xmpp:%!s(&lt;nil&gt;)?join} <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}" from=foo1foo2@conf.testjabber.autonomia.digital
```
This third line is still logged but when this happens the user is being notified,  also related to #773.
```
ERRO[0287] Something wrong happened during the request   account=olatest@testjabber.autonomia.digital component=session error="received an error from the server" requestType=create-reserved-room where=mucRequest
```
The last line is only printed in debug mode:
```
DEBU[0352] getRoomView(): trying to get a not connected room  account=olatest@testjabber.autonomia.digital component=gui room=foo1foo3@conf.testjabber.autonomia.digital
```

From now on we will focus on this remaining error log: 
```
ERRO[0352] Got a presence error                          account=olatest@testjabber.autonomia.digital component=session error="&{{jabber:client error}   cancel  {{ } } <nil> <nil> <nil> <nil> <nil> <nil> <nil> 0xc0004925e0 <nil> <nil>}" from=foo1foo3@conf.testjabber.autonomia.digital
```

**Comment by azlancpool** [comment]
We have noticed that the presence errors are related to the initial necessary presence sent in order to create a room. So, we decided to implement a strategy in order to avoid the noise generated by those presences.

**Comment by olabiniV2** [comment]
OK
