### ISSUE TITLE
Highlighting of fields jump when moving around in room configuration

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#776]
If you start creating a configured room, type in a description, then press the summary button, and then press the "Basic information" tab, the focus will be moved to "Primary language of discussion".

**Comment by olabiniV2** [comment]
The above commit fixes this issue - see this comment in #772 for a deeper explanation: https://github.com/coyim/coyim/issues/772#issuecomment-909838023

**Comment by IvanJijon** [comment]
Reviewed by the team, it looks good.
