### ISSUE TITLE
Missing icon when creating a new room without auto-join

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#779]
On my Tails environment, with a new build, if you create a room, configure it but not put auto-join, you get a "congratulations" page. It's supposed to contain an icon, but it seems to be missing.
![Screenshot from 2021-09-02 21-55-03](https://user-images.githubusercontent.com/52427592/131921893-c8064ca0-e66d-4577-b42b-7cce0aa06bba.png)

**Comment by azlancpool** [comment]
`user-test` was successful

**Comment by olabiniV2** [comment]
OK
