### ISSUE TITLE
SCRAM-SHA-512-PLUS authentication fails with ejabberd 21.0.7

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#783]
The error seems to be related to channel binding.

**Comment by olabiniV2** [comment]
The `-PLUS` versions of SCRAM uses channel binding. However, this channel binding changes in TLS 1.3. Specifically, `tls-unique` is used before TLS 1.3, but `tls-unique` is not defined for TLS 1.3. Thus, the Golang libraries return `nil` when asked for a channel binding on a TLS 1.3 connection. The `-PLUS` versions of SCRAM have recently (May 2021) been redefined to use the `tls-exporter` channel binding on TLS 1.3. However, the Golang libraries do not expose functionality for getting this channel binding, and doesn't expose the information necessary to create it on client side. For this reason, it's not possible to use the `-PLUS` SCRAM versions for TLS 1.3. To work around this, we disable those as possible mechanisms in the case of TLS 1.3. 

We should revisit this in a year or two, when hopefully Golang supports the `tls-exporter` channel binding mechanism.

**Comment by azlancpool** [comment]
`user-test` was successul

**Comment by olabiniV2** [comment]
@azlancpool @IvanJijon @peterpalau @sacurio I can't do the code review for this one, since it's my own code. Can one of you please do it?

**Comment by azlancpool** [comment]
Reviewed, OK

**Comment by Neustradamus** [comment]
@olabini, @olabiniV2, @azlancpool, @Cris2760: It is official for TLS 1.3 Binding!
- RFC 9266: Channel Bindings for TLS 1.3: https://tools.ietf.org/html/rfc9266

Details:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

PR: https://github.com/coyim/coyim/pull/845
