### ISSUE TITLE
Translations should be bundled in the binary and available without source code

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#791]
The current translation functionality only works if you are running the CoyIM binary in the same directory that contains the `i18n` directory. That makes it fine for developers, but useless for users.

Because of how `gettext` works, this is not so easy to fix. You can't read translation strings from memory. At the same time, we want to continue using `gettext` because that is what GLib and GTK uses. This also makes all translateable strings in the UI definitions automatically work. So moving away from `gettext` is not realistic right now.

What we will do instead is that we will package up the `.mo` files into a zip file and include that in the CoyIM binary. Then, at startup, we will check the application data directory and see if translations are already there. If they are, we will ensure they came from the same commit as the running CoyIM. If not, we will remove it and unzip the translations there, making them available for the `gettext` implementation to use.

This was found as part of #787

**Comment by IvanJijon** [comment]
Reviewed by the team, OK.
