### ISSUE TITLE
A warning occurs when disconnect / reconnecting notifications appear.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#811]
CoyIM:1133126): Gtk-WARNING **: 15:38:52.448: Attempting to add a widget with type GtkBox to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.

**Comment by azlancpool** [comment]
This warning was appearing because we were adding the same widget into the containing box. In order to prevent this warning we remove the widget always before adding it. Solved in e171b49

**Comment by azlancpool** [comment]
Approved in `user-test`, it's ready to `code-review`

**Comment by olabiniV2** [comment]
OK
