### ISSUE TITLE
In a members-only room, remove an occupant when their affiliation changes to "none"

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#813]
- It is necessary to verify the server notifications.
- Check the behavior of Prosody.

**Comment by azlancpool** [comment]
We checked the server notifications received and we noticed that we are not handling the status code `321`, this is specified in XEP-0045 (see: https://xmpp.org/extensions/xep-0045.html#revokemember)
Considering that we should update the issue name

**Comment by azlancpool** [comment]
>     * It is necessary to verify the server notifications.
> 
>     * Check the behavior of Prosody.

We must keep an eye on:

- Update roster panel.
- Show a notification in second person to the `self-occupant` removed from the room.
- Notify through the conversation view to the other occupants (and the `self-occupant` too).
- Disable send-message box for `self-occupant`, and show a message related with this.
- Update the behaviour of `edit-subject` component.
- Disable room in general.

**Comment by IvanJijon** [comment]
It was decided in `user-test` to replace "members only" by "members-only" in messages shown to users.

**Comment by IvanJijon** [comment]
Ready for `code-review`.

**Comment by olabiniV2** [comment]
OK
