### ISSUE TITLE
Mac DMG is not compatible with Mojave (1.14)

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#818]
When downloading the Mac DMG on Mojave (macOS 1.14) and try to run it, you get an error message because the mac integration (version 3.4) library bundled inside it seems to be built for Catalina (macOS 1.15).

We need to investigate whether it's possible to build for older versions using homebrow or Github Actions, and if not, decide if macOS 1.15 as the oldest supported version is acceptable.

**Comment by olabiniV2** [comment]
After looking up compatitbility, Mojave is still supported by Apple. High Sierra is not. So ideally, we should support Mojave and forward.

**Comment by olabiniV2** [comment]
OK, some of the previous commits have tried to build on Github Actions using a Mojave build of gtk-mac-integration. It's not clear whether this will work or not yet. The tag https://github.com/coyim/coyim/releases/tag/test-mac-mojave-1 has been created to collect a build of this, and others in the office will try it on Mojave and see if it actually works or not.

If it doesn't work, we have two alrnatives. One is to create our own self-hosted runners with Mojave in the office. This will be expensive and annoying to manage. The other choice is to use another service that has Mojave runners to create the specific build we need. Some of the above commits put back a specific Travis file, focused only on creating a Mojave compatible DMG. This is currently in testing.

**Comment by olabiniV2** [comment]
If we can't get Travis working well for our purposes, we might also try Azure pipelines

**Comment by olabiniV2** [comment]
We now have working DMG generation that is compatible with Mojave running on travis. As such, this issue is ready to be tested.

**Comment by azlancpool** [comment]
Reviewed by the team, OK
