### ISSUE TITLE
Add rooms to @coy.im

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#820]
We should support MUC on the XMPP server for coy.im, so that we can create #support and #welcome rooms there, at least.

**Comment by guschiriboga** [comment]
Rooms were created

![image](https://user-images.githubusercontent.com/22728524/134389912-11d37343-3a8a-4fe9-92d1-bf89957c5c40.png)

**Comment by olabiniV2** [comment]
OK, OK, this has been done. The rooms created are `users@conf.coy.im`, `support@conf.coy.im` and `dev@conf.coy.im`
