### ISSUE TITLE
nb_NO for 0.4?

### ISSUE THREAD

**Issue by comradekingu** [coyim/coyim#830]
I finished https://hosted.weblate.org/projects/coyim/main/nb_NO/ to find
the ship sailed for https://github.com/coyim/coyim/commit/cd96c50e67797af115677227a9e6bb03433e582f

Getting the e-mails for (those?) changes to source strings, and subsequent new strings for translations is what got me started me on this quest.

The source strings are very verbose, and there are some errors. I don't have it in me to deal with all of that now,
but have the worst of it marked as "needing review" in nb_NO.

**Comment by olabiniV2** [comment]
Fantastic, thank you so much. The pre-release has been tagged already, but we can certainly include your work in the final 0.4 release coming in a few weeks. Thanks so much for your hard work!
