### ISSUE TITLE
Correct icons in dark mode for the configuration assistant

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#833]
This is now only focused on making the navigation bar for the config assistant in MUC look good in both dark and light themes. The larger work of moving CoyIM to handle all this stuff properly everywhere will require some preparatory refactoring that is not appropriate for the 0.4 release. I will open a new issue to track this.

**Comment by azlancpool** [comment]
A way to know if coy is using a dark theme is looking at the background colour of the current open window.
We are working on it now.

**Comment by azlancpool** [comment]
We already upload icons of the room configuration view for dark themes in: eb25594f2086d6f0d67db30bb2dd5726b79f69ad

**Comment by IvanJijon** [comment]
This story was validated in User Test.

**Comment by olabiniV2** [comment]
OK
