### ISSUE TITLE
Group Chat, Channel Categories

### ISSUE THREAD

**Issue by Pantyhose-X** [coyim/coyim#846]
### Feature request
Command
`/##`
`/#announcemenet#`  "Create a channel with the name `announcemenet`"
`#announcemenet` hello monocles  "Message Sync to `announcemenet` category"

![](https://user-images.githubusercontent.com/42504385/165966010-068fc5a4-76a6-49da-a43c-a05e20726424.png)

### Why this feature is need
With a group of 100 people, the speeches would be chaotic.
Number of people 1k,10k,100k,1000k, 😱

With the Channel Categories feature, it is the best choice for the team, like discord, rvlt.gg, are developing very well, I believe coyim will be better

**Comment by olabiniV2** [comment]
Sorry, I'm a bit confused by this request. What is the behavior you are looking for in terms of XMPP MUC?

**Comment by Pantyhose-X** [comment]
Allow users to Liberty Create Thread
Thread time, for 1 year. or forever
Only groups, administrators and creators, can delete Thread channels

can feel like an ocean sometimes with walls of text rapidly flooding your screen. Interesting conversations can be confusing to follow in the middle of other conversations and may just disappear entirely.

**Comment by olabiniV2** [comment]
Sorry, we still don't really understand this feature request. Remember also that CoyIM only supports what XMPP supports.
