### ISSUE TITLE
Add Go Modules support

### ISSUE THREAD

**Issue by aaronjheng** [coyim/coyim#855]
Please consider.

**Comment by aryanvarma7272** [comment]
Hey @aaronjheng , How can I add Go Modules support , can you explain in brief...

**Comment by aaronjheng** [comment]
Thanks for your reply. @aryanvarma7272
It has been added in https://github.com/coyim/coyim/commit/ae03a91268cdd781f029aa6056b1ac0e9deac973.
Closing.
