### ISSUE TITLE
XEP-0388: Extensible SASL Profile support

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#862]
Dear @coyim team, @olabiniV2,

After jabber.ru MITM, can you add the support of "XEP-0388: Extensible SASL Profile" in CoyIM for more security?
- https://xmpp.org/extensions/xep-0388.html

Thanks in advance.

Linked to:
- https://github.com/coyim/coyim/issues/847
- https://github.com/coyim/coyim/issues/863
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

**Comment by olabiniV2** [comment]
As mentioned in other issues, channel binding has nothing to do with the `jabber.ru` case. This is an experimental XEP, and as far as I can tell, there is no server that supports it.
