### ISSUE TITLE
XEP-0440: SASL Channel-Binding Type Capability support

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#863]
Dear @coyim team, @olabiniV2,

After jabber.ru MITM, can you add the support of "XEP-0440: SASL Channel-Binding Type Capability" in CoyIM for more security?
- https://xmpp.org/extensions/xep-0440.html

Thanks in advance.

Linked to:
- https://github.com/coyim/coyim/issues/847
- https://github.com/coyim/coyim/issues/862
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

**Comment by olabiniV2** [comment]
As mentioned in the many other issues you have spammed us with, this has nothing to do with the `jabber.ru` case, and neither are there servers with support. Finally, it is an experimental XEP.

**Comment by Neustradamus** [comment]
@olabiniV2: Thanks for your message.

It is strange, several XMPP Clients and XMPP Servers already support it.

I think it is not serious to close unsolved tickets.
